package murat.simv2.analysis;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Track 1 of the Option-C generator: emits the real-&gt;sim bridge (the {@code SimPlayerState}
 * struct and the player-state capture) from the movement-field manifest, so the bridge is no
 * longer hand-maintained. Re-running the WALA analysis on a new Minecraft version regenerates it.
 *
 * <p>The player-state bridge is a CODIFIED POLICY reconciled against the manifest, not a blind
 * projection: the validated minimal state mixes manifest-backed fields (pos, velocity, yaw,
 * pitch, onGround, horizontalCollision, jumping, flying) with getter-derived / sim-internal
 * fields (sprinting, movementSpeed, stepHeight, verticalCollision) that are not manifest entries.
 * Every manifest-backed field is validated to still exist in {@code movement-fields.txt}; if an MC
 * update renames or drops one, generation FAILS loudly rather than silently producing a wrong
 * bridge. The world-snapshot capture is a delegate layer and stays hand-written (see Captures).
 *
 * <p>Usage: {@code BridgeGenerator <manifest.txt> <generated-java-root>}
 */
public final class BridgeGenerator {

    private static final String GEN_HEADER =
        "// GENERATED by murat.simv2.analysis.BridgeGenerator from movement-fields.txt — DO NOT EDIT.\n"
            + "// Regenerate with: ./gradlew :analysis:generateBridge\n";

    /** One field of the generated SimPlayerState + how to capture it from a live player. */
    private record FieldSpec(
        String name,
        String javaType,
        String initExpr,
        String captureExpr,   // null => sim-managed, not synced from the player
        String manifestKey,   // "dotClass fieldName" to validate against the manifest, or null
        String note
    ) {
    }

    // The validated on-land bridge, codified. manifestKey entries are drift-checked.
    private static final List<FieldSpec> STATE = List.of(
        new FieldSpec("pos", "Vec3", "Vec3.ZERO", "toVec3(player.getPos())",
            "net.minecraft.entity.Entity pos", "entity position (the seed field)"),
        new FieldSpec("velocity", "Vec3", "Vec3.ZERO", "toVec3(player.getVelocity())",
            "net.minecraft.entity.Entity velocity", "entity velocity"),
        new FieldSpec("yaw", "float", "0.0f", "player.getYaw()",
            "net.minecraft.entity.Entity yaw", "body yaw, drives input rotation"),
        new FieldSpec("pitch", "float", "0.0f", "player.getPitch()",
            "net.minecraft.entity.Entity pitch", "pitch (needed for gliding)"),
        new FieldSpec("onGround", "boolean", "false", "player.isOnGround()",
            "net.minecraft.entity.Entity onGround", "ground flag, gates friction/speed"),
        new FieldSpec("horizontalCollision", "boolean", "false", null,
            "net.minecraft.entity.Entity horizontalCollision", "sim output, set by move()"),
        new FieldSpec("verticalCollision", "boolean", "false", null,
            null, "sim output, set by move()"),
        new FieldSpec("sprinting", "boolean", "false", "player.isSprinting()",
            null, "DataTracker-derived; off-ground sprint speed boost"),
        new FieldSpec("jumping", "boolean", "false", null,
            "net.minecraft.entity.LivingEntity jumping", "jump input (sim-applied)"),
        new FieldSpec("flying", "boolean", "false", "player.getAbilities().flying",
            "net.minecraft.entity.player.PlayerAbilities flying", "creative/spectator flight"),
        // float (not double): MC's LivingEntity.movementSpeed is a float field and getMovementSpeed(F)
        // computes the whole speed in float — widening to double here diverges bit-for-bit.
        new FieldSpec("movementSpeed", "float", "0.1f", "player.getMovementSpeed()",
            null, "MOVEMENT_SPEED attribute value this tick (incl. sprint/effects)"),
        new FieldSpec("stepHeight", "double", "DEFAULT_STEP_HEIGHT", "player.getStepHeight()",
            null, "auto step-up height"),
        new FieldSpec("flySpeed", "float", "0.05f", "player.getAbilities().getFlySpeed()",
            null, "creative fly speed (off-ground speed when flying)"),
        // double (not float): getAttributeValue(JUMP_STRENGTH) returns a double; getJumpVelocity(F)
        // narrows to float INSIDE the transpiled physics. A float field here would double-round.
        new FieldSpec("jumpStrength", "double", "0.42",
            "player.getAttributeValue(net.minecraft.entity.attribute.EntityAttributes.JUMP_STRENGTH)",
            null, "JUMP_STRENGTH attribute (vanilla 0.42); base jump velocity")
    );

    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            throw new IllegalArgumentException("Usage: BridgeGenerator <manifest.txt> <generated-java-root>");
        }
        Path manifest = Path.of(args[0]);
        Path javaRoot = Path.of(args[1]);

        Set<String> manifestKeys = parseManifestKeys(manifest);
        validateAgainstManifest(manifestKeys);

        // Self-heal: SimPlayerState is a generated class now. If a legacy hand-written copy lingers
        // in src/main/java (e.g. left over from before codegen, or from a partial sync), it would
        // collide with the generated one as a duplicate class. Remove it so the build is reliable.
        deleteLegacyHandwritten(javaRoot);

        Path simDir = javaRoot.resolve("murat/simv2/sim");
        Path harnessDir = javaRoot.resolve("murat/simv2/harness");
        Files.createDirectories(simDir);
        Files.createDirectories(harnessDir);

        Files.writeString(simDir.resolve("SimPlayerState.java"), emitSimPlayerState());
        Files.writeString(harnessDir.resolve("PlayerStateCapture.java"), emitPlayerStateCapture());

        System.out.println("BridgeGenerator: emitted SimPlayerState + PlayerStateCapture ("
            + STATE.size() + " fields, "
            + STATE.stream().filter(f -> f.captureExpr() != null).count() + " synced) to " + javaRoot);
    }

    /** Remove a legacy hand-written generated-class file in src/main/java, if present. */
    private static void deleteLegacyHandwritten(Path javaRoot) throws IOException {
        // javaRoot = <repo>/src/main/generated/java  ->  legacy = <repo>/src/main/java/...
        Path srcMain = javaRoot.getParent().getParent();
        Path legacy = srcMain.resolve("java/murat/simv2/sim/SimPlayerState.java");
        if (Files.deleteIfExists(legacy)) {
            System.out.println("BridgeGenerator: removed legacy hand-written " + legacy
                + " (SimPlayerState is generated; the stale copy would be a duplicate class)");
        }
    }

    private static Set<String> parseManifestKeys(Path manifest) throws IOException {
        Set<String> keys = new HashSet<>();
        for (String line : Files.readAllLines(manifest)) {
            String t = line.strip();
            if (t.isEmpty() || t.startsWith("#")) continue;
            // <category> <declaringClass> <fieldName> <descriptor>
            String[] parts = t.split("\\s+");
            if (parts.length >= 4) {
                keys.add(parts[1] + " " + parts[2]);
            }
        }
        return keys;
    }

    private static void validateAgainstManifest(Set<String> manifestKeys) {
        List<String> missing = new ArrayList<>();
        for (FieldSpec f : STATE) {
            if (f.manifestKey() != null && !manifestKeys.contains(f.manifestKey())) {
                missing.add(f.name() + " -> '" + f.manifestKey() + "'");
            }
        }
        if (!missing.isEmpty()) {
            throw new IllegalStateException(
                "Bridge/manifest drift: CORE state fields no longer present in movement-fields.txt: "
                    + missing + ". The Minecraft mappings likely changed; update BridgeGenerator.STATE.");
        }
    }

    private static String emitSimPlayerState() {
        StringBuilder b = new StringBuilder();
        b.append("package murat.simv2.sim;\n\n");
        b.append(GEN_HEADER);
        b.append("\n/**\n")
            .append(" * Mutable per-rollout movement state. Generated from the movement-field manifest;\n")
            .append(" * a rollout mutates one instance in place each tick (allocation-light for mass rollouts).\n")
            .append(" */\n");
        b.append("public final class SimPlayerState {\n");
        b.append("    // Standing player hitbox (EntityType.PLAYER dimensions).\n");
        b.append("    public static final double WIDTH = 0.6;\n");
        b.append("    public static final double HEIGHT = 1.8;\n");
        b.append("    public static final double DEFAULT_STEP_HEIGHT = 0.6;\n\n");
        for (FieldSpec f : STATE) {
            b.append("    public ").append(f.javaType()).append(' ').append(f.name())
                .append(" = ").append(f.initExpr()).append(";");
            if (f.note() != null) b.append("  // ").append(f.note());
            b.append('\n');
        }
        b.append("\n    public AABB boundingBox() {\n");
        b.append("        return AABB.ofEntity(pos, WIDTH, HEIGHT);\n");
        b.append("    }\n\n");
        b.append("    public SimPlayerState copy() {\n");
        b.append("        SimPlayerState c = new SimPlayerState();\n");
        for (FieldSpec f : STATE) {
            b.append("        c.").append(f.name()).append(" = ").append(f.name()).append(";\n");
        }
        b.append("        return c;\n");
        b.append("    }\n");
        b.append("}\n");
        return b.toString();
    }

    private static String emitPlayerStateCapture() {
        StringBuilder b = new StringBuilder();
        b.append("package murat.simv2.harness;\n\n");
        b.append(GEN_HEADER);
        b.append("\nimport murat.simv2.sim.SimPlayerState;\n");
        b.append("import murat.simv2.sim.Vec3;\n");
        b.append("import net.minecraft.entity.player.PlayerEntity;\n");
        b.append("import net.minecraft.util.math.Vec3d;\n\n");
        b.append("/**\n")
            .append(" * Real-&gt;sim player-state bridge. Generated from the movement-field manifest: each synced\n")
            .append(" * field is read from a public getter (no access-widener needed for the on-land set).\n")
            .append(" * The world snapshot is captured separately by the hand-written Captures (a delegate layer).\n")
            .append(" */\n");
        b.append("public final class PlayerStateCapture {\n");
        b.append("    private PlayerStateCapture() {\n    }\n\n");
        b.append("    public static SimPlayerState capturePlayer(PlayerEntity player) {\n");
        b.append("        SimPlayerState s = new SimPlayerState();\n");
        for (FieldSpec f : STATE) {
            if (f.captureExpr() == null) continue;
            b.append("        s.").append(f.name()).append(" = ").append(f.captureExpr()).append(";\n");
        }
        b.append("        return s;\n");
        b.append("    }\n\n");
        b.append("    static Vec3 toVec3(Vec3d v) {\n");
        b.append("        return new Vec3(v.x, v.y, v.z);\n");
        b.append("    }\n");
        b.append("}\n");
        return b.toString();
    }

    private BridgeGenerator() {
    }
}
