package murat.simv2.analysis;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.InnerClassNode;
import org.objectweb.asm.tree.MethodNode;

/**
 * Emits stub Java sources for closure classes that don't have a {@code .java}
 * entry in the sources jar. The stub mirrors the bytecode shape (super class,
 * interfaces, fields, methods, nested types) closely enough that any
 * reference to the type from a transformed primary source will compile.
 *
 * <p>Method bodies are no-ops with default returns. Field initializers are
 * defaulted as well — these stubs are never executed in the simulator;
 * they only exist to make the mirror module a self-consistent type graph.
 */
final class MirrorBytecodeStubber {
    private static final String MIRROR_PACKAGE_PREFIX = "murat.simv2.simulation.mirror.";

    private final Map<String, ClassNode> nodesByInternal;
    private final Set<String> emittedTopLevels = new HashSet<>();

    MirrorBytecodeStubber(Path mcJar) throws IOException {
        this.nodesByInternal = readClassNodes(mcJar);
    }

    /**
     * Emits the mirror file containing {@code dotClass}. Because nested
     * classes share a file with their top-level, we emit the top-level
     * shell plus the entire nested type tree in one shot, then return
     * {@code true} for any further requests against classes inside that
     * top-level (idempotent).
     */
    boolean emitStub(String dotClass, Path mirrorRoot) {
        String topLevel = dotClass;
        int dollar = topLevel.indexOf('$');
        if (dollar >= 0) {
            topLevel = topLevel.substring(0, dollar);
        }
        if (!emittedTopLevels.add(topLevel)) {
            return true;
        }
        ClassNode root = nodesByInternal.get(topLevel.replace('.', '/'));
        if (root == null) {
            // Anonymous inner class (e.g. Foo$1) without a top-level — skip.
            return false;
        }

        StringBuilder source = new StringBuilder();
        source.append("package ").append(MIRROR_PACKAGE_PREFIX)
            .append(packageOf(topLevel)).append(";\n\n");
        source.append("// Generated bytecode-stub mirror. Do not edit.\n");
        emitType(root, source, 0);

        Path target = mirrorRoot.resolve(topLevel.replace('.', '/') + ".java");
        try {
            Files.createDirectories(target.getParent());
            Files.writeString(target, source.toString());
        } catch (IOException ex) {
            System.err.println("Failed to write stub for " + topLevel + ": " + ex.getMessage());
            return false;
        }
        return true;
    }

    private void emitType(ClassNode cn, StringBuilder sb, int indent) {
        boolean isInterface = (cn.access & Opcodes.ACC_INTERFACE) != 0;
        boolean isEnum = (cn.access & Opcodes.ACC_ENUM) != 0;
        boolean isAnnotation = (cn.access & Opcodes.ACC_ANNOTATION) != 0;

        appendIndent(sb, indent);
        sb.append("public ");
        if (indent > 0 && (cn.access & Opcodes.ACC_STATIC) != 0) {
            sb.append("static ");
        }
        if (isAnnotation) {
            sb.append("@interface ");
        } else if (isInterface) {
            sb.append("interface ");
        } else if (isEnum) {
            sb.append("enum ");
        } else {
            // Use abstract for everything else so we don't have to satisfy
            // every abstract super method.
            sb.append("abstract class ");
        }
        sb.append(simpleNameOf(internalToDot(cn.name)));

        if (!isInterface && !isEnum && !isAnnotation && cn.superName != null
            && !"java/lang/Object".equals(cn.superName)) {
            sb.append(" extends ").append(rewrittenTypeName(cn.superName));
        }
        if (!isAnnotation && !cn.interfaces.isEmpty()) {
            String keyword = isInterface ? " extends " : " implements ";
            sb.append(keyword);
            for (int i = 0; i < cn.interfaces.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(rewrittenTypeName(cn.interfaces.get(i)));
            }
        }
        sb.append(" {\n");

        if (isEnum) {
            // Pull declared enum constants from the static final fields.
            List<String> constants = new ArrayList<>();
            for (FieldNode f : cn.fields) {
                if ((f.access & Opcodes.ACC_ENUM) != 0) {
                    constants.add(f.name);
                }
            }
            if (constants.isEmpty()) {
                appendIndent(sb, indent + 1);
                sb.append(";\n\n");
            } else {
                appendIndent(sb, indent + 1);
                for (int i = 0; i < constants.size(); i++) {
                    if (i > 0) sb.append(", ");
                    sb.append(safeIdentifier(constants.get(i)));
                }
                sb.append(";\n\n");
            }
        }

        Map<String, ClassNode> nestedByName = collectNestedTypes(cn);

        if (!isAnnotation) {
            for (FieldNode field : cn.fields) {
                if ((field.access & Opcodes.ACC_ENUM) != 0) continue;
                if ((field.access & Opcodes.ACC_SYNTHETIC) != 0) continue;
                emitField(field, sb, indent + 1, isInterface);
            }
            for (MethodNode method : cn.methods) {
                if ((method.access & Opcodes.ACC_SYNTHETIC) != 0) continue;
                if ((method.access & Opcodes.ACC_BRIDGE) != 0) continue;
                if ("<clinit>".equals(method.name)) continue;
                emitMethod(method, cn, sb, indent + 1, isInterface, isEnum);
            }
            if (!isInterface && !isEnum && !hasUserConstructor(cn)) {
                appendIndent(sb, indent + 1);
                sb.append("public ").append(simpleNameOf(internalToDot(cn.name))).append("() { }\n\n");
            }
        }

        for (ClassNode nested : nestedByName.values()) {
            emitType(nested, sb, indent + 1);
        }

        appendIndent(sb, indent);
        sb.append("}\n");
    }

    private Map<String, ClassNode> collectNestedTypes(ClassNode owner) {
        Map<String, ClassNode> nested = new LinkedHashMap<>();
        if (owner.innerClasses == null) return nested;
        for (InnerClassNode inner : owner.innerClasses) {
            if (inner.outerName == null || !inner.outerName.equals(owner.name)) continue;
            if (inner.innerName == null) continue;
            ClassNode child = nodesByInternal.get(inner.name);
            if (child != null) {
                nested.put(inner.name, child);
            }
        }
        return nested;
    }

    private void emitField(FieldNode field, StringBuilder sb, int indent, boolean inInterface) {
        appendIndent(sb, indent);
        if (inInterface) {
            sb.append("public static final ");
        } else {
            sb.append("public ");
            if ((field.access & Opcodes.ACC_STATIC) != 0) sb.append("static ");
        }
        String typeName = renderType(Type.getType(field.desc));
        sb.append(typeName).append(' ').append(safeIdentifier(field.name));
        if (inInterface || (field.access & Opcodes.ACC_STATIC) != 0
            || (field.access & Opcodes.ACC_FINAL) != 0) {
            sb.append(" = ").append(defaultValueLiteral(typeName));
        }
        sb.append(";\n");
    }

    private void emitMethod(MethodNode method, ClassNode declaring,
                            StringBuilder sb, int indent,
                            boolean inInterface, boolean inEnum) {
        boolean isCtor = "<init>".equals(method.name);
        boolean isStatic = (method.access & Opcodes.ACC_STATIC) != 0;
        boolean isAbstract = (method.access & Opcodes.ACC_ABSTRACT) != 0;
        if (isCtor && (inEnum || inInterface)) return;

        appendIndent(sb, indent);
        if (inInterface) {
            sb.append(isAbstract ? "" : "default ");
        } else {
            sb.append("public ");
            if (isStatic) sb.append("static ");
        }
        Type methodType = Type.getMethodType(method.desc);
        if (isCtor) {
            sb.append(simpleNameOf(internalToDot(declaring.name)));
        } else {
            sb.append(renderType(methodType.getReturnType())).append(' ').append(safeIdentifier(method.name));
        }
        sb.append('(');
        Type[] argTypes = methodType.getArgumentTypes();
        for (int i = 0; i < argTypes.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(renderType(argTypes[i])).append(" arg").append(i);
        }
        sb.append(')');

        if (isAbstract && !inInterface) {
            // We declared the class abstract; abstract methods don't need bodies.
            // But our class might be enum or stub-class — emit a body anyway.
            sb.append(" {");
            appendDefaultBody(methodType.getReturnType(), sb);
            sb.append(" }\n");
            return;
        }
        sb.append(" {");
        if (isCtor) {
            sb.append(" /* stub */ ");
        } else {
            appendDefaultBody(methodType.getReturnType(), sb);
        }
        sb.append("}\n");
    }

    private boolean hasUserConstructor(ClassNode cn) {
        for (MethodNode m : cn.methods) {
            if ("<init>".equals(m.name) && m.desc.startsWith("()")) return true;
        }
        return false;
    }

    private void appendDefaultBody(Type returnType, StringBuilder sb) {
        if (returnType == Type.VOID_TYPE) return;
        sb.append(" return ").append(defaultValueLiteral(renderType(returnType))).append("; ");
    }

    private String defaultValueLiteral(String typeName) {
        return switch (typeName) {
            case "boolean" -> "false";
            case "byte"    -> "(byte) 0";
            case "char"    -> "'\\0'";
            case "short"   -> "(short) 0";
            case "int"     -> "0";
            case "long"    -> "0L";
            case "float"   -> "0.0f";
            case "double"  -> "0.0";
            default        -> "null";
        };
    }

    private String renderType(Type type) {
        switch (type.getSort()) {
            case Type.VOID:    return "void";
            case Type.BOOLEAN: return "boolean";
            case Type.BYTE:    return "byte";
            case Type.CHAR:    return "char";
            case Type.SHORT:   return "short";
            case Type.INT:     return "int";
            case Type.LONG:    return "long";
            case Type.FLOAT:   return "float";
            case Type.DOUBLE:  return "double";
            case Type.ARRAY:   return renderType(type.getElementType()) + "[]".repeat(type.getDimensions());
            case Type.OBJECT:  return rewrittenTypeName(type.getInternalName());
            default:           return "java.lang.Object";
        }
    }

    private String rewrittenTypeName(String internalName) {
        if (internalName == null) return "java.lang.Object";
        String dot = internalToDot(internalName);
        if (dot.startsWith("net.minecraft.")) {
            return MIRROR_PACKAGE_PREFIX + dot;
        }
        return dot;
    }

    private static String internalToDot(String internalName) {
        return internalName.replace('/', '.').replace('$', '.');
    }

    private static String simpleNameOf(String dotName) {
        int dot = dotName.lastIndexOf('.');
        return dot < 0 ? dotName : dotName.substring(dot + 1);
    }

    private static String packageOf(String dotName) {
        int dot = dotName.lastIndexOf('.');
        return dot < 0 ? "" : dotName.substring(0, dot);
    }

    private static String safeIdentifier(String name) {
        // Mojang names occasionally include reserved words after remapping.
        return switch (name) {
            case "abstract", "assert", "boolean", "break", "byte", "case", "catch",
                 "char", "class", "const", "continue", "default", "do", "double",
                 "else", "enum", "extends", "final", "finally", "float", "for",
                 "goto", "if", "implements", "import", "instanceof", "int",
                 "interface", "long", "native", "new", "package", "private",
                 "protected", "public", "return", "short", "static", "strictfp",
                 "super", "switch", "synchronized", "this", "throw", "throws",
                 "transient", "try", "void", "volatile", "while", "true", "false",
                 "null", "yield", "var", "record", "sealed" -> name + "_";
            default -> name;
        };
    }

    private static void appendIndent(StringBuilder sb, int indent) {
        for (int i = 0; i < indent; i++) sb.append("    ");
    }

    private static Map<String, ClassNode> readClassNodes(Path mcJar) throws IOException {
        Map<String, ClassNode> out = new LinkedHashMap<>();
        try (JarFile jar = new JarFile(mcJar.toFile())) {
            var enumeration = jar.entries();
            while (enumeration.hasMoreElements()) {
                JarEntry entry = enumeration.nextElement();
                if (entry.isDirectory() || !entry.getName().endsWith(".class")) continue;
                if (!entry.getName().startsWith("net/minecraft/")) continue;
                ClassNode cn = new ClassNode();
                try (var in = jar.getInputStream(entry)) {
                    new ClassReader(in.readAllBytes()).accept(cn, ClassReader.SKIP_CODE);
                }
                out.put(cn.name, cn);
            }
        }
        return out;
    }

    /** For diagnostics only. */
    @SuppressWarnings("unused")
    Set<String> internalNames() {
        return new TreeSet<>(nodesByInternal.keySet());
    }
}
