package murat.simv2.analysis;

import com.google.gson.Gson;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Track-2 (Option C) transpiler — GO/NO-GO prototype. Reads {@code movement-ir.json} (the captured
 * WALA SSA IR) and emits standalone, Minecraft-free Java for movement methods.
 *
 * <p>Emission strategy: a block DISPATCH LOOP ({@code while(true) switch(block)}). This is
 * correctness-preserving for any (even irreducible) CFG and sidesteps general control-flow
 * reconstruction; readable structuring is a later optimisation. Out-of-SSA is done by assigning
 * phi targets on the predecessor edge. Exceptional successors are pruned (movement physics ignores
 * exception flow). Float/double widths are taken from the IR's conversions/types, so the arithmetic
 * matches Minecraft bit-for-bit; calls are routed PHYSICS/WORLD/MATH per a table (unrouted calls
 * throw — never silently dropped).
 *
 * <p>This prototype targets {@code Entity.movementInputToVelocity}, the input-rotation method —
 * it exercises the full machinery (a branch, a phi, MATH routing, float/double conversions,
 * typed constants) and is validated bit-exact against the golden {@code MovementSim} in tests.
 */
public final class SimGenerator {

    private static final String TARGET_NAME = "movementInputToVelocity";

    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            throw new IllegalArgumentException("Usage: SimGenerator <movement-ir.json> <generated-java-root>");
        }
        Path ir = Path.of(args[0]);
        Path javaRoot = Path.of(args[1]);

        Map<String, Object> root;
        try (Reader r = Files.newBufferedReader(ir)) {
            root = new Gson().fromJson(r, Map.class);
        }
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> methods = (List<Map<String, Object>>) root.get("methods");

        Map<String, Object> target = null;
        for (Map<String, Object> m : methods) {
            if (TARGET_NAME.equals(m.get("name"))) {
                target = m;
                break;
            }
        }
        if (target == null) {
            throw new IllegalStateException("Target method not found in IR: " + TARGET_NAME);
        }

        String body = new MethodTranspiler(target).emit();
        String cls = """
            package murat.simv2.sim.gen;

            // GENERATED by murat.simv2.analysis.SimGenerator from movement-ir.json — DO NOT EDIT.

            import murat.simv2.sim.Vec3;
            import murat.simv2.sim.MathHelperPort;
            import murat.simv2.sim.SimRuntime;

            /** Transpiled standalone movement methods (Option C, Track 2). */
            public final class GeneratedMovement {
                private GeneratedMovement() {
                }

            %s
            }
            """.formatted(body);

        Path outDir = javaRoot.resolve("murat/simv2/sim/gen");
        Files.createDirectories(outDir);
        Files.writeString(outDir.resolve("GeneratedMovement.java"), cls);
        System.out.println("SimGenerator: emitted GeneratedMovement." + TARGET_NAME + " -> " + outDir);
    }

    /** Transpiles one method record to a dispatch-loop Java method. */
    private static final class MethodTranspiler {
        private final Map<String, Object> method;
        private final Map<Integer, Map<String, Object>> constByVn = new TreeMap<>();
        private final Map<Integer, String> typeByVn = new TreeMap<>();
        private final Map<Integer, Map<String, Object>> blockById = new TreeMap<>();

        MethodTranspiler(Map<String, Object> method) {
            this.method = method;
            for (Map<String, Object> c : list(method.get("constants"))) {
                constByVn.put(i(c.get("vn")), c);
            }
            for (Map<String, Object> t : list(method.get("types"))) {
                typeByVn.put(i(t.get("vn")), (String) t.get("type"));
            }
            for (Map<String, Object> b : list(method.get("blocks"))) {
                blockById.put(i(b.get("id")), b);
            }
        }

        String emit() {
            String name = (String) method.get("name");
            String descriptor = (String) method.get("descriptor");
            List<Map<String, Object>> params = list(method.get("params"));

            StringBuilder sb = new StringBuilder();
            // signature
            List<String> paramDecls = new ArrayList<>();
            java.util.Set<Integer> paramVns = new java.util.HashSet<>();
            for (Map<String, Object> p : params) {
                int vn = i(p.get("vn"));
                paramVns.add(vn);
                paramDecls.add(javaType((String) p.get("type")) + " v" + vn);
            }
            String ret = javaType(returnTypeOf(descriptor));
            sb.append("    public static ").append(ret).append(' ').append(name)
                .append('(').append(String.join(", ", paramDecls)).append(") {\n");

            // local declarations for every def (insn + phi) that isn't a param/constant
            java.util.Set<Integer> defs = new java.util.TreeSet<>();
            for (Map<String, Object> b : blockById.values()) {
                for (Map<String, Object> phi : list(b.get("phis"))) defs.add(i(phi.get("def")));
                for (Map<String, Object> in : list(b.get("insns"))) {
                    if (in.containsKey("def")) defs.add(i(in.get("def")));
                }
            }
            for (int vn : defs) {
                if (paramVns.contains(vn) || constByVn.containsKey(vn)) continue;
                String jt = javaType(typeByVn.getOrDefault(vn, "I"));
                sb.append("        ").append(jt).append(" v").append(vn).append(" = ")
                    .append(defaultValue(jt)).append(";\n");
            }

            int entry = entryBlockId();
            sb.append("        int $b = ").append(entry).append(";\n");
            sb.append("        while (true) {\n            switch ($b) {\n");
            for (Map<String, Object> b : blockById.values()) {
                if (list(b.get("insns")).isEmpty() && list(b.get("phis")).isEmpty()
                    && normalSucc(b).isEmpty()) {
                    continue; // unreachable/exit-only block
                }
                sb.append("                case ").append(i(b.get("id"))).append(": {\n");
                emitBlock(b, sb);
                sb.append("                }\n");
            }
            sb.append("                default: throw new IllegalStateException(\"bad block \" + $b);\n");
            sb.append("            }\n        }\n    }\n");
            return sb.toString();
        }

        private void emitBlock(Map<String, Object> b, StringBuilder sb) {
            List<Map<String, Object>> insns = list(b.get("insns"));
            Map<String, Object> terminator = null;
            for (Map<String, Object> in : insns) {
                String op = (String) in.get("op");
                if (op.equals("cbranch") || op.equals("goto") || op.equals("return")) {
                    terminator = in;
                    continue;
                }
                String stmt = emitInsn(in);
                if (stmt != null) sb.append("                    ").append(stmt).append('\n');
            }
            int from = i(b.get("id"));
            if (terminator == null) {
                List<Integer> ns = normalSucc(b);
                if (ns.size() == 1) {
                    sb.append(edgeAssign(from, ns.get(0)));
                    sb.append("                    $b = ").append(ns.get(0)).append("; break;\n");
                } else {
                    sb.append("                    break;\n");
                }
                return;
            }
            String op = (String) terminator.get("op");
            switch (op) {
                case "return" -> {
                    List<Integer> uses = intList(terminator.get("uses"));
                    sb.append("                    return ")
                        .append(uses.isEmpty() ? "" : operand(uses.get(0))).append(";\n");
                }
                case "goto" -> {
                    int to = targetBlock(i(terminator.get("target")));
                    sb.append(edgeAssign(from, to));
                    sb.append("                    $b = ").append(to).append("; break;\n");
                }
                case "cbranch" -> {
                    List<Integer> uses = intList(terminator.get("uses"));
                    int taken = targetBlock(i(terminator.get("target")));
                    int fall = -1;
                    for (int s : normalSucc(b)) if (s != taken) { fall = s; break; }
                    String rel = relop((String) terminator.get("operator"));
                    sb.append("                    if (").append(operand(uses.get(0))).append(' ')
                        .append(rel).append(' ').append(operand(uses.get(1))).append(") {\n");
                    sb.append(indent(edgeAssign(from, taken)));
                    sb.append("                        $b = ").append(taken).append(";\n");
                    sb.append("                    } else {\n");
                    sb.append(indent(edgeAssign(from, fall)));
                    sb.append("                        $b = ").append(fall).append(";\n");
                    sb.append("                    }\n                    break;\n");
                }
                default -> throw new IllegalStateException("unexpected terminator " + op);
            }
        }

        /** Statement for a non-terminator instruction (or null to skip). */
        private String emitInsn(Map<String, Object> in) {
            String op = (String) in.get("op");
            switch (op) {
                case "new":
                    return null; // the matching <init> invoke assigns the value
                case "binop": {
                    List<Integer> u = intList(in.get("uses"));
                    return assign(in, operand(u.get(0)) + " " + arith((String) in.get("operator"))
                        + " " + operand(u.get(1)));
                }
                case "unop": {
                    List<Integer> u = intList(in.get("uses"));
                    return assign(in, "-" + operand(u.get(0))); // only neg occurs
                }
                case "conversion": {
                    List<Integer> u = intList(in.get("uses"));
                    return assign(in, "(" + javaType((String) in.get("to")) + ") " + operand(u.get(0)));
                }
                case "compare": {
                    List<Integer> u = intList(in.get("uses"));
                    String fn = "cmpg".equals(in.get("operator")) ? "cmpg" : "cmpl";
                    return assign(in, "SimRuntime." + fn + "(" + operand(u.get(0)) + ", "
                        + operand(u.get(1)) + ")");
                }
                case "getfield": {
                    String acc = fieldAccessor(field(in));
                    return assign(in, operand(i(in.get("ref"))) + "." + acc);
                }
                case "getstatic": {
                    Map<String, Object> f = field(in);
                    if ("Lnet/minecraft/util/math/Vec3d".equals(f.get("class")) && "ZERO".equals(f.get("name"))) {
                        return assign(in, "Vec3.ZERO");
                    }
                    throw new IllegalStateException("unrouted getstatic " + f);
                }
                case "invoke":
                    return emitInvoke(in);
                default:
                    throw new IllegalStateException("unsupported op in transpile: " + op + " " + in);
            }
        }

        private String emitInvoke(Map<String, Object> in) {
            String target = (String) in.get("target");
            List<Integer> u = intList(in.get("uses"));
            String selector = target.substring(target.indexOf('#') + 1);
            if (selector.startsWith("<init>")) {
                String type = javaType(target.substring(0, target.indexOf('#')));
                List<String> args = new ArrayList<>();
                for (int k = 1; k < u.size(); k++) args.add(operand(u.get(k)));
                return "v" + u.get(0) + " = new " + type + "(" + String.join(", ", args) + ");";
            }
            String expr = routeCall(target, u);
            if (in.containsKey("def")) {
                return "v" + i(in.get("def")) + " = " + expr + ";";
            }
            return expr + ";";
        }

        /** PHYSICS/WORLD/MATH routing for the prototype's call surface (unrouted -> throw). */
        private String routeCall(String target, List<Integer> u) {
            return switch (target) {
                case "Lnet/minecraft/util/math/Vec3d#lengthSquared()D" ->
                    operand(u.get(0)) + ".lengthSquared()";
                case "Lnet/minecraft/util/math/Vec3d#normalize()Lnet/minecraft/util/math/Vec3d;" ->
                    operand(u.get(0)) + ".normalize()";
                case "Lnet/minecraft/util/math/Vec3d#multiply(D)Lnet/minecraft/util/math/Vec3d;" ->
                    operand(u.get(0)) + ".scale(" + operand(u.get(1)) + ")";
                case "Lnet/minecraft/util/math/MathHelper#sin(F)F" ->
                    "MathHelperPort.sin(" + operand(u.get(0)) + ")";
                case "Lnet/minecraft/util/math/MathHelper#cos(F)F" ->
                    "MathHelperPort.cos(" + operand(u.get(0)) + ")";
                default -> throw new IllegalStateException("unrouted call: " + target);
            };
        }

        // --- edge / phi handling ---

        private String edgeAssign(int from, int to) {
            Map<String, Object> toBlock = blockById.get(to);
            if (toBlock == null) return "";
            List<Map<String, Object>> phis = list(toBlock.get("phis"));
            if (phis.isEmpty()) return "";
            List<Integer> preds = intList(toBlock.get("pred"));
            int idx = preds.indexOf(from);
            StringBuilder sb = new StringBuilder();
            for (Map<String, Object> phi : phis) {
                List<Integer> uses = intList(phi.get("uses"));
                int operandVn = uses.get(idx);
                sb.append("                    v").append(i(phi.get("def"))).append(" = ")
                    .append(operand(operandVn)).append(";\n");
            }
            return sb.toString();
        }

        // --- helpers ---

        private String assign(Map<String, Object> in, String expr) {
            return "v" + i(in.get("def")) + " = " + expr + ";";
        }

        private String operand(int vn) {
            Map<String, Object> c = constByVn.get(vn);
            if (c == null) return "v" + vn;
            return literal((String) c.get("kind"), c.get("value"));
        }

        private String literal(String kind, Object value) {
            return switch (kind) {
                case "int" -> Integer.toString((int) Math.rint(((Number) value).doubleValue()));
                case "long" -> ((long) ((Number) value).longValue()) + "L";
                case "boolean" -> Boolean.toString(Boolean.TRUE.equals(value));
                case "double" -> doubleLiteral(value);
                case "float" -> floatLiteral(value);
                case "null" -> "null";
                default -> throw new IllegalStateException("unhandled const kind " + kind);
            };
        }

        private String doubleLiteral(Object value) {
            if (value instanceof String s) {
                return switch (s) {
                    case "NaN" -> "Double.NaN";
                    case "Infinity" -> "Double.POSITIVE_INFINITY";
                    case "-Infinity" -> "Double.NEGATIVE_INFINITY";
                    default -> throw new IllegalStateException("bad double token " + s);
                };
            }
            return Double.toString(((Number) value).doubleValue());
        }

        private String floatLiteral(Object value) {
            if (value instanceof String s) {
                return switch (s) {
                    case "NaN" -> "Float.NaN";
                    case "Infinity" -> "Float.POSITIVE_INFINITY";
                    case "-Infinity" -> "Float.NEGATIVE_INFINITY";
                    default -> throw new IllegalStateException("bad float token " + s);
                };
            }
            return Double.toString(((Number) value).doubleValue()) + "f";
        }

        private int entryBlockId() {
            for (Map<String, Object> b : blockById.values()) {
                if (Boolean.TRUE.equals(b.get("entry"))) return i(b.get("id"));
            }
            return blockById.keySet().iterator().next();
        }

        private List<Integer> normalSucc(Map<String, Object> b) {
            List<Integer> succ = intList(b.get("succ"));
            List<Integer> exc = intList(b.get("excSucc"));
            List<Integer> out = new ArrayList<>();
            for (int s : succ) if (!exc.contains(s)) out.add(s);
            return out;
        }

        private int targetBlock(int targetIindex) {
            for (Map<String, Object> b : blockById.values()) {
                if (i(b.get("firstInsn")) == targetIindex) return i(b.get("id"));
            }
            throw new IllegalStateException("no block with firstInsn " + targetIindex);
        }

        @SuppressWarnings("unchecked")
        private Map<String, Object> field(Map<String, Object> in) {
            return (Map<String, Object>) in.get("field");
        }

        private String fieldAccessor(Map<String, Object> f) {
            if ("Lnet/minecraft/util/math/Vec3d".equals(f.get("class"))) {
                String n = (String) f.get("name");
                if (n.equals("x") || n.equals("y") || n.equals("z")) return n + "()";
            }
            throw new IllegalStateException("unrouted field access " + f);
        }

        private static String returnTypeOf(String descriptor) {
            return descriptor.substring(descriptor.indexOf(')') + 1);
        }

        private static String javaType(String wala) {
            return switch (wala) {
                case "D" -> "double";
                case "F" -> "float";
                case "I" -> "int";
                case "Z" -> "boolean";
                case "J" -> "long";
                case "B" -> "byte";
                case "S" -> "short";
                case "C" -> "char";
                case "V" -> "void";
                case "Lnet/minecraft/util/math/Vec3d", "Lnet/minecraft/util/math/Vec3d;" -> "Vec3";
                default -> throw new IllegalStateException("unmapped type " + wala);
            };
        }

        private static String defaultValue(String javaType) {
            return switch (javaType) {
                case "double" -> "0.0";
                case "float" -> "0.0f";
                case "int", "byte", "short", "char" -> "0";
                case "long" -> "0L";
                case "boolean" -> "false";
                default -> "null";
            };
        }

        private static String arith(String op) {
            return switch (op) {
                case "add" -> "+";
                case "sub" -> "-";
                case "mul" -> "*";
                case "div" -> "/";
                case "rem" -> "%";
                default -> throw new IllegalStateException("unhandled binop " + op);
            };
        }

        private static String relop(String op) {
            return switch (op) {
                case "eq" -> "==";
                case "ne" -> "!=";
                case "lt" -> "<";
                case "ge" -> ">=";
                case "gt" -> ">";
                case "le" -> "<=";
                default -> throw new IllegalStateException("unhandled relop " + op);
            };
        }

        private static String indent(String block) {
            if (block.isEmpty()) return "";
            StringBuilder sb = new StringBuilder();
            for (String line : block.split("\n", -1)) {
                if (!line.isEmpty()) sb.append("    ").append(line).append('\n');
            }
            return sb.toString();
        }
    }

    // --- generic JSON helpers (Gson decodes numbers as Double) ---

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> list(Object o) {
        return o == null ? List.of() : (List<Map<String, Object>>) o;
    }

    private static List<Integer> intList(Object o) {
        List<Integer> out = new ArrayList<>();
        if (o instanceof List<?> l) for (Object e : l) out.add(i(e));
        return out;
    }

    private static int i(Object o) {
        return (int) Math.rint(((Number) o).doubleValue());
    }

    private SimGenerator() {
    }
}
