package murat.simv2.analysis;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Code-generates the sink-gating Mixins from the WALA-derived
 * {@code sink-callsites.txt}.
 *
 * <p>One Mixin per <em>effect-owning</em> class; one
 * {@link org.spongepowered.asm.mixin.injection.Inject @Inject} at the
 * {@code HEAD} of each effect method that returns immediately when
 * {@code murat.simv2.predict.Prediction.isActive()}. The guard is
 * <em>callee-side</em> (inside the effect method), so every caller — chain
 * classes, the {@code tickables} loop, data-tracker callbacks, a deferred
 * enqueue, reflection — is suppressed on the prediction thread, with zero
 * real-game impact (the flag is thread-scoped). No hand-listed gate; the set
 * re-derives mechanically for whatever MC jar the analysis ran on.
 *
 * <p>Outputs (under the analysis output dir, which is
 * {@code src/main/generated}):
 * <ul>
 *   <li>{@code java/murat/simv2/mixin/gen/Gen*SinkMixin.java}</li>
 *   <li>{@code sim-v2.gen.mixins.json}</li>
 * </ul>
 */
final class SinkMixinEmitter {

    private static final String PKG = "murat.simv2.mixin.gen";
    private static final String FLAG = "murat.simv2.predict.Prediction.isActive()";

    private SinkMixinEmitter() {
    }

    static void emit(Path outputDir, TreeSet<String> sinkCallsites) throws IOException {
        Path genDir = outputDir.resolve("java")
            .resolve("murat").resolve("simv2").resolve("mixin").resolve("gen");
        Files.createDirectories(genDir);
        // Drop stale generated mixins so a previous MC version's gates can
        // never linger and fail to compile / over-gate.
        try (var s = Files.list(genDir)) {
            for (Path p : s.toList()) {
                if (p.getFileName().toString().endsWith(".java")) {
                    Files.delete(p);
                }
            }
        }

        // ownerSlash -> set of [calleeName, calleeDesc, S|I].
        Map<String, LinkedHashSet<String[]>> byOwner = new TreeMap<>();
        for (String line : sinkCallsites) {
            String[] p = line.split("\\|");
            if (p.length < 3) {
                continue;
            }
            String mod = p.length >= 4 ? p[3] : "I";
            byOwner.computeIfAbsent(p[0], k -> new LinkedHashSet<>())
                .add(new String[] {p[1], p[2], mod});
        }

        TreeSet<String> mixinClasses = new TreeSet<>();
        Map<String, String> nameToOwner = new TreeMap<>();
        int redirects = 0;
        for (var e : byOwner.entrySet()) {
            String ownerSlash = e.getKey();
            String simple = ownerSlash.substring(ownerSlash.lastIndexOf('/') + 1)
                .replace('$', '_');
            String mixinName = "Gen" + simple + "SinkMixin";
            // Disambiguate the rare case of two distinct owners with the same
            // simple name (e.g. a.Foo vs b.Foo) so neither file is lost.
            if (nameToOwner.containsKey(mixinName)
                && !nameToOwner.get(mixinName).equals(ownerSlash)) {
                mixinName = mixinName + "_"
                    + Integer.toHexString(ownerSlash.hashCode() & 0xffff);
            }
            nameToOwner.put(mixinName, ownerSlash);
            mixinClasses.add(mixinName);
            String src = renderMixin(mixinName, ownerSlash, e.getValue());
            redirects += e.getValue().size();
            Files.write(genDir.resolve(mixinName + ".java"),
                src.getBytes(StandardCharsets.UTF_8));
        }

        Files.write(outputDir.resolve("sim-v2.gen.mixins.json"),
            renderJson(mixinClasses).getBytes(StandardCharsets.UTF_8));

        System.out.printf(
            "Generated gates: %d mixin(s), %d redirect(s) -> %s%n",
            mixinClasses.size(), redirects, genDir);
    }

    private static String renderMixin(
        String mixinName, String ownerSlash, LinkedHashSet<String[]> methods) {
        StringBuilder b = new StringBuilder();
        b.append("package ").append(PKG).append(";\n\n")
            .append("import org.spongepowered.asm.mixin.Mixin;\n")
            .append("import org.spongepowered.asm.mixin.injection.At;\n")
            .append("import org.spongepowered.asm.mixin.injection.Inject;\n")
            .append("import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;\n")
            .append("import org.spongepowered.asm.mixin.injection.callback."
                + "CallbackInfoReturnable;\n\n")
            .append("/** Generated by SinkMixinEmitter — do not edit. "
                + "Callee-side effect gate. */\n")
            .append("@Mixin(targets = \"").append(ownerSlash).append("\")\n")
            .append("public abstract class ").append(mixinName).append(" {\n");

        int idx = 0;
        for (String[] s : methods) {
            String name = s[0];
            String desc = s[1];
            boolean isStatic = s.length >= 3 && "S".equals(s[2]);
            List<String> argTypes = new ArrayList<>();
            String retType = parseDescriptor(desc, argTypes);
            boolean isVoid = "void".equals(retType);
            boolean isPrimitive = !isVoid && switch (retType) {
                case "boolean", "byte", "char", "short",
                     "int", "long", "float", "double" -> true;
                default -> false;
            };
            String handler = "simv2$g" + (idx++);
            String selector = name + desc;

            String cbType = isVoid ? "CallbackInfo"
                : isPrimitive
                    ? "CallbackInfoReturnable<" + boxed(retType) + ">"
                    : "CallbackInfoReturnable<Object>";
            String cbVar = isVoid ? "ci" : "cir";
            // Explicit descriptor selector disambiguates overloads.
            // require = 1: fail-loud. Each generated gate MUST bind to a real
            // method body — a non-binding @Inject (e.g. an abstract owner
            // whose body lives in a subtype) now fails mixin APPLY at load
            // instead of silently no-op'ing and leaking the effect into the
            // real game. SinkEffectAnalysis resolves every leaf to its
            // concrete declarer so the set is exact for this mapping.
            // Mixin requires the callback's static-ness to match the target;
            // a static effect leaf needs a `private static` handler or APPLY
            // fails ("non-static callback targets a static method").
            b.append("\n    @Inject(method = \"").append(selector)
                .append("\", at = @At(\"HEAD\"), cancellable = true, "
                    + "require = 1)\n")
                .append("    private ").append(isStatic ? "static " : "")
                .append("void ").append(handler)
                .append('(').append(cbType).append(' ').append(cbVar)
                .append(") {\n")
                .append("        if (").append(FLAG).append(") { ");
            if (isVoid) {
                b.append(cbVar).append(".cancel();");
            } else {
                b.append(cbVar).append(".setReturnValue(")
                    .append(isPrimitive ? defaultLiteral(retType) : "null")
                    .append(");");
            }
            b.append(" }\n    }\n");
        }
        b.append("}\n");
        return b.toString();
    }

    private static String renderJson(TreeSet<String> mixinClasses) {
        StringBuilder b = new StringBuilder();
        b.append("{\n")
            .append("\t\"required\": true,\n")
            .append("\t\"package\": \"").append(PKG).append("\",\n")
            .append("\t\"compatibilityLevel\": \"JAVA_21\",\n")
            .append("\t\"client\": [");
        int i = 0;
        for (String c : mixinClasses) {
            b.append(i++ == 0 ? "\n" : ",\n").append("\t\t\"").append(c).append('"');
        }
        b.append(mixinClasses.isEmpty() ? "" : "\n\t").append("],\n")
            .append("\t\"injectors\": {\n\t\t\"defaultRequire\": 1\n\t}\n}\n");
        return b.toString();
    }

    /** Parses {@code (args)ret} JVM descriptor → Java source types. */
    private static String parseDescriptor(String desc, List<String> argsOut) {
        int i = desc.indexOf('(') + 1;
        int end = desc.indexOf(')');
        while (i < end) {
            int[] next = new int[1];
            argsOut.add(readType(desc, i, next));
            i = next[0];
        }
        int[] next = new int[1];
        return readType(desc, end + 1, next);
    }

    /** Reads one JVM type token at {@code i}; sets {@code next[0]} past it. */
    private static String readType(String s, int i, int[] next) {
        int dims = 0;
        while (s.charAt(i) == '[') {
            dims++;
            i++;
        }
        char c = s.charAt(i);
        String base;
        if (c == 'L') {
            int semi = s.indexOf(';', i);
            base = internalToJava(s.substring(i + 1, semi));
            next[0] = semi + 1;
        } else {
            base = switch (c) {
                case 'V' -> "void";
                case 'Z' -> "boolean";
                case 'B' -> "byte";
                case 'C' -> "char";
                case 'S' -> "short";
                case 'I' -> "int";
                case 'J' -> "long";
                case 'F' -> "float";
                case 'D' -> "double";
                default -> throw new IllegalArgumentException(
                    "Bad descriptor '" + s + "' at " + i);
            };
            next[0] = i + 1;
        }
        return base + "[]".repeat(dims);
    }

    private static String internalToJava(String internal) {
        return internal.replace('/', '.').replace('$', '.');
    }

    private static String defaultLiteral(String javaType) {
        return switch (javaType) {
            case "boolean" -> "false";
            case "long" -> "0L";
            case "float" -> "0.0F";
            case "double" -> "0.0";
            case "byte", "char", "short", "int" -> "0";
            default -> "null"; // object / array
        };
    }

    /** Wrapper type for an {@code Operation<…>} type argument (no primitives). */
    private static String boxed(String javaType) {
        return switch (javaType) {
            case "void" -> "Void";
            case "boolean" -> "Boolean";
            case "byte" -> "Byte";
            case "char" -> "Character";
            case "short" -> "Short";
            case "int" -> "Integer";
            case "long" -> "Long";
            case "float" -> "Float";
            case "double" -> "Double";
            default -> javaType; // object / array
        };
    }
}
