package murat.simv2.analysis;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Code-generates the sink-gating Mixins from the WALA-derived
 * {@code sink-callsites.txt}.
 *
 * <p>One Mixin per caller class (the entry supertype chain); one
 * {@link org.spongepowered.asm.mixin.injection.Redirect @Redirect} per
 * distinct callee signature in that caller, skipping the call when
 * {@code murat.simv2.predict.Prediction.ACTIVE}. Caller-side redirection is
 * uniform — it handles void/non-void, abstract callees and polymorphic block
 * callbacks identically — so there is no hand-listed gate and the set
 * re-derives mechanically for whatever MC jar the analysis ran on.
 *
 * <p>Outputs (under the analysis output dir, which is
 * {@code src/main/generated}):
 * <ul>
 *   <li>{@code java/murat/simv2/mixin/gen/Gen*SinkMixin.java}</li>
 *   <li>{@code sim-v2.gen.mixins.json}</li>
 * </ul>
 */
final class SinkMixinEmitter {

    private static final String PKG = "murat.simv2.mixin.gen";
    private static final String FLAG = "murat.simv2.predict.Prediction.ACTIVE";

    private SinkMixinEmitter() {
    }

    static void emit(Path outputDir, TreeSet<String> sinkCallsites) throws IOException {
        Path genDir = outputDir.resolve("java")
            .resolve("murat").resolve("simv2").resolve("mixin").resolve("gen");
        Files.createDirectories(genDir);
        // Drop stale generated mixins so a previous MC version's gates can
        // never linger and fail to compile / over-gate.
        try (var s = Files.list(genDir)) {
            for (Path p : s.toList()) {
                if (p.getFileName().toString().endsWith(".java")) {
                    Files.delete(p);
                }
            }
        }

        // callerClassDot -> set of [callerSelector, calleeOwner, calleeName,
        // calleeDesc, kind].
        Map<String, LinkedHashSet<String[]>> byCaller = new TreeMap<>();
        for (String line : sinkCallsites) {
            String[] p = line.split("\\|");
            if (p.length < 6) {
                continue;
            }
            byCaller.computeIfAbsent(p[0], k -> new LinkedHashSet<>())
                .add(new String[] {p[1], p[2], p[3], p[4], p[5]});
        }

        TreeSet<String> mixinClasses = new TreeSet<>();
        int redirects = 0;
        for (var e : byCaller.entrySet()) {
            String callerDot = e.getKey();
            String simple = callerDot.substring(callerDot.lastIndexOf('.') + 1)
                .replace('$', '_');
            String mixinName = "Gen" + simple + "SinkMixin";
            mixinClasses.add(mixinName);
            String src = renderMixin(mixinName, callerDot, e.getValue());
            redirects += e.getValue().size();
            Files.write(genDir.resolve(mixinName + ".java"),
                src.getBytes(StandardCharsets.UTF_8));
        }

        Files.write(outputDir.resolve("sim-v2.gen.mixins.json"),
            renderJson(mixinClasses).getBytes(StandardCharsets.UTF_8));

        System.out.printf(
            "Generated gates: %d mixin(s), %d redirect(s) -> %s%n",
            mixinClasses.size(), redirects, genDir);
    }

    private static String renderMixin(
        String mixinName, String callerDot, LinkedHashSet<String[]> sinks) {
        String callerSlash = callerDot.replace('.', '/');
        StringBuilder b = new StringBuilder();
        b.append("package ").append(PKG).append(";\n\n")
            .append("import com.llamalad7.mixinextras.injector.wrapoperation.Operation;\n")
            .append("import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;\n")
            .append("import org.spongepowered.asm.mixin.Mixin;\n")
            .append("import org.spongepowered.asm.mixin.injection.At;\n\n")
            .append("/** Generated by SinkMixinEmitter from sink-callsites.txt — do not edit. */\n")
            .append("@Mixin(targets = \"").append(callerSlash).append("\")\n")
            .append("public abstract class ").append(mixinName).append(" {\n");

        int idx = 0;
        for (String[] s : sinks) {
            String callerSelector = s[0];
            String calleeOwnerSlash = s[1];
            String calleeName = s[2];
            String calleeDesc = s[3];
            boolean isStatic = "STATIC".equals(s[4]);

            List<String> argTypes = new ArrayList<>();
            String retType = parseDescriptor(calleeDesc, argTypes);
            String ownerJava = internalToJava(calleeOwnerSlash);
            String target = "L" + calleeOwnerSlash + ";" + calleeName + calleeDesc;
            String handler = "simv2$g" + (idx++);

            StringBuilder params = new StringBuilder();
            StringBuilder callArgs = new StringBuilder();
            if (!isStatic) {
                params.append(ownerJava).append(" recv");
                callArgs.append("recv");
            }
            for (int i = 0; i < argTypes.size(); i++) {
                if (params.length() > 0) {
                    params.append(", ");
                }
                params.append(argTypes.get(i)).append(" a").append(i);
                if (callArgs.length() > 0) {
                    callArgs.append(", ");
                }
                callArgs.append("a").append(i);
            }
            if (params.length() > 0) {
                params.append(", ");
            }
            params.append("Operation<").append(boxed(retType)).append("> original");
            boolean isVoid = "void".equals(retType);

            // @WrapOperation performs the original via original.call(...), so
            // protected/private/static/void callees all work uniformly and
            // there is never a visibility problem (the @Redirect failure mode).
            b.append("\n    @WrapOperation(method = \"").append(callerSelector)
                .append("\", at = @At(value = \"INVOKE\", target = \"")
                .append(target).append("\"))\n")
                .append("    private ").append(retType).append(' ')
                .append(handler).append('(').append(params).append(") {\n");
            if (isVoid) {
                b.append("        if (").append(FLAG).append(") { return; }\n")
                    .append("        original.call(").append(callArgs).append(");\n");
            } else {
                b.append("        if (").append(FLAG).append(") { return ")
                    .append(defaultLiteral(retType)).append("; }\n")
                    .append("        return original.call(").append(callArgs).append(");\n");
            }
            b.append("    }\n");
        }
        b.append("}\n");
        return b.toString();
    }

    private static String renderJson(TreeSet<String> mixinClasses) {
        StringBuilder b = new StringBuilder();
        b.append("{\n")
            .append("\t\"required\": true,\n")
            .append("\t\"package\": \"").append(PKG).append("\",\n")
            .append("\t\"compatibilityLevel\": \"JAVA_21\",\n")
            .append("\t\"client\": [");
        int i = 0;
        for (String c : mixinClasses) {
            b.append(i++ == 0 ? "\n" : ",\n").append("\t\t\"").append(c).append('"');
        }
        b.append(mixinClasses.isEmpty() ? "" : "\n\t").append("],\n")
            .append("\t\"injectors\": {\n\t\t\"defaultRequire\": 1\n\t}\n}\n");
        return b.toString();
    }

    /** Parses {@code (args)ret} JVM descriptor → Java source types. */
    private static String parseDescriptor(String desc, List<String> argsOut) {
        int i = desc.indexOf('(') + 1;
        int end = desc.indexOf(')');
        while (i < end) {
            int[] next = new int[1];
            argsOut.add(readType(desc, i, next));
            i = next[0];
        }
        int[] next = new int[1];
        return readType(desc, end + 1, next);
    }

    /** Reads one JVM type token at {@code i}; sets {@code next[0]} past it. */
    private static String readType(String s, int i, int[] next) {
        int dims = 0;
        while (s.charAt(i) == '[') {
            dims++;
            i++;
        }
        char c = s.charAt(i);
        String base;
        if (c == 'L') {
            int semi = s.indexOf(';', i);
            base = internalToJava(s.substring(i + 1, semi));
            next[0] = semi + 1;
        } else {
            base = switch (c) {
                case 'V' -> "void";
                case 'Z' -> "boolean";
                case 'B' -> "byte";
                case 'C' -> "char";
                case 'S' -> "short";
                case 'I' -> "int";
                case 'J' -> "long";
                case 'F' -> "float";
                case 'D' -> "double";
                default -> throw new IllegalArgumentException(
                    "Bad descriptor '" + s + "' at " + i);
            };
            next[0] = i + 1;
        }
        return base + "[]".repeat(dims);
    }

    private static String internalToJava(String internal) {
        return internal.replace('/', '.').replace('$', '.');
    }

    private static String defaultLiteral(String javaType) {
        return switch (javaType) {
            case "boolean" -> "false";
            case "long" -> "0L";
            case "float" -> "0.0F";
            case "double" -> "0.0";
            case "byte", "char", "short", "int" -> "0";
            default -> "null"; // object / array
        };
    }

    /** Wrapper type for an {@code Operation<…>} type argument (no primitives). */
    private static String boxed(String javaType) {
        return switch (javaType) {
            case "void" -> "Void";
            case "boolean" -> "Boolean";
            case "byte" -> "Byte";
            case "char" -> "Character";
            case "short" -> "Short";
            case "int" -> "Integer";
            case "long" -> "Long";
            case "float" -> "Float";
            case "double" -> "Double";
            default -> javaType; // object / array
        };
    }
}
