package murat.simv2.analysis;

import spoon.Launcher;
import spoon.reflect.CtModel;
import spoon.reflect.code.*;
import spoon.reflect.declaration.*;
import spoon.reflect.visitor.CtScanner;
import spoon.reflect.visitor.filter.TypeFilter;

import java.io.IOException;
import java.nio.file.*;
import java.util.*;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

/**
 * Uses Spoon to read decompiled Minecraft sources and prune statements
 * not present in the WALA backward slice, producing a movement-only class.
 */
public class SpoonSlicePruner {

    private final Path sourcesJar;
    private final Map<String, Map<String, Set<Integer>>> sliceLines;

    public SpoonSlicePruner(Path sourcesJar, Map<String, Map<String, Set<Integer>>> sliceLines) {
        this.sourcesJar = sourcesJar;
        this.sliceLines = sliceLines;
    }

    public void pruneAndWrite(Path outputDir) throws IOException {
        // Extract sources from JAR to temp directory
        Path tempDir = Files.createTempDirectory("mc-sources-");
        try {
            extractTargetSources(tempDir);

            // Build Spoon model (no-classpath mode — we only need AST structure)
            System.out.println("Building Spoon model...");
            Launcher launcher = new Launcher();
            launcher.addInputResource(tempDir.toString());
            launcher.getEnvironment().setNoClasspath(true);
            launcher.getEnvironment().setComplianceLevel(21);
            launcher.getEnvironment().setAutoImports(true);
            launcher.buildModel();
            CtModel model = launcher.getModel();
            System.out.println("Spoon model: " + model.getAllTypes().size() + " types loaded");

            // Process each target class
            for (String className : AnalysisConfig.TARGET_CLASSES_DOT) {
                Map<String, Set<Integer>> methodLines = sliceLines.get(className);
                if (methodLines == null || methodLines.isEmpty()) {
                    System.out.println("  No slice data for " + className + " — skipping");
                    continue;
                }

                CtType<?> type = model.getAllTypes().stream()
                    .filter(t -> t.getQualifiedName().equals(className))
                    .findFirst()
                    .orElse(null);

                if (type == null) {
                    System.err.println("  Type not found in Spoon model: " + className);
                    continue;
                }

                pruneClass(type, methodLines, outputDir);
            }
        } finally {
            // Clean up temp directory
            try (var walk = Files.walk(tempDir)) {
                walk.sorted(Comparator.reverseOrder()).map(Path::toFile).forEach(java.io.File::delete);
            }
        }
    }

    private void extractTargetSources(Path tempDir) throws IOException {
        System.out.println("Extracting target sources from " + sourcesJar.getFileName() + "...");

        // Build set of paths to extract
        Set<String> targetPaths = new HashSet<>();
        for (String className : AnalysisConfig.TARGET_CLASSES_DOT) {
            targetPaths.add(className.replace('.', '/') + ".java");
        }

        try (JarFile jar = new JarFile(sourcesJar.toFile())) {
            Enumeration<JarEntry> entries = jar.entries();
            while (entries.hasMoreElements()) {
                JarEntry entry = entries.nextElement();
                if (entry.isDirectory()) continue;

                if (targetPaths.contains(entry.getName())) {
                    Path outFile = tempDir.resolve(entry.getName());
                    Files.createDirectories(outFile.getParent());
                    try (var in = jar.getInputStream(entry)) {
                        Files.copy(in, outFile);
                    }
                    System.out.println("  Extracted: " + entry.getName());
                }
            }
        }
    }

    private void pruneClass(CtType<?> type, Map<String, Set<Integer>> methodLines, Path outputDir) throws IOException {
        String simpleName = type.getSimpleName();
        System.out.println("Pruning " + type.getQualifiedName() + "...");

        StringBuilder sb = new StringBuilder();
        sb.append("package murat.simv2.simulation.sliced;\n\n");
        sb.append("// Sliced from ").append(type.getQualifiedName()).append("\n");
        sb.append("// Contains only statements that affect movement (pos/velocity/onGround/fallDistance/boundingBox)\n");
        sb.append("// Generated by WALA backward slice + Spoon AST pruning — do not edit\n\n");

        for (var entry : methodLines.entrySet()) {
            String methodSelector = entry.getKey();
            Set<Integer> keepLines = entry.getValue();

            // Find the method name (strip descriptor)
            String methodName = methodSelector.substring(0, methodSelector.indexOf('('));

            // Find the method in the type
            CtMethod<?> method = findMethod(type, methodName);
            if (method == null) {
                System.out.println("  Method not found: " + methodName + " in " + simpleName);
                continue;
            }

            // Clone the method so we don't modify the original model
            CtMethod<?> cloned = method.clone();

            // Prune statements not in the slice
            int before = countStatements(cloned);
            pruneMethod(cloned, keepLines);
            int after = countStatements(cloned);

            System.out.println("  " + simpleName + "." + methodName + "(): "
                + before + " → " + after + " statements ("
                + keepLines.size() + " slice lines)");

            sb.append("// From ").append(simpleName).append("\n");
            sb.append(cloned.toString()).append("\n\n");
        }

        // Write output
        Path outFile = outputDir.resolve("Sliced" + simpleName + ".java");
        Files.createDirectories(outFile.getParent());
        Files.writeString(outFile, sb.toString());
        System.out.println("  Wrote " + outFile.getFileName());
    }

    private CtMethod<?> findMethod(CtType<?> type, String methodName) {
        for (CtMethod<?> m : type.getMethods()) {
            if (m.getSimpleName().equals(methodName)) {
                return m;
            }
        }
        return null;
    }

    private void pruneMethod(CtMethod<?> method, Set<Integer> keepLines) {
        if (method.getBody() == null) return;

        List<CtStatement> allStatements = method.getBody()
            .filterChildren(new TypeFilter<>(CtStatement.class))
            .list();

        // Collect statements to remove, then delete in reverse order (children first)
        List<CtStatement> toRemove = new ArrayList<>();
        for (CtStatement statement : allStatements) {
            if (statement.getPosition() != null && statement.getPosition().isValidPosition()) {
                int lineNumber = statement.getPosition().getLine();
                if (!keepLines.contains(lineNumber) && !hasSlicedChild(statement, keepLines)) {
                    toRemove.add(statement);
                }
            }
        }

        for (int i = toRemove.size() - 1; i >= 0; i--) {
            try {
                toRemove.get(i).delete();
            } catch (Exception e) {
                // Statement may have been removed as part of a parent deletion
            }
        }
    }

    private boolean hasSlicedChild(CtElement element, Set<Integer> keepLines) {
        List<CtStatement> children = element.filterChildren(new TypeFilter<>(CtStatement.class)).list();
        for (CtStatement child : children) {
            if (child == element) continue;
            if (child.getPosition() != null && child.getPosition().isValidPosition()) {
                if (keepLines.contains(child.getPosition().getLine())) {
                    return true;
                }
            }
        }
        return false;
    }

    private int countStatements(CtMethod<?> method) {
        int[] count = {0};
        if (method.getBody() != null) {
            method.getBody().accept(new CtScanner() {
                @Override
                public void scan(CtElement element) {
                    if (element instanceof CtStatement && !(element instanceof CtBlock)) {
                        count[0]++;
                    }
                    super.scan(element);
                }
            });
        }
        return count[0];
    }
}
