package murat.simv2.analysis;

import com.ibm.wala.classLoader.IClass;
import com.ibm.wala.classLoader.IField;
import com.ibm.wala.classLoader.IMethod;
import com.ibm.wala.ipa.cha.IClassHierarchy;
import com.ibm.wala.types.TypeReference;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

public class SyncCodeGenerator {

    private final IClassHierarchy cha;
    private final Path outputDir;

    public SyncCodeGenerator(IClassHierarchy cha, Path outputDir) {
        this.cha = cha;
        this.outputDir = outputDir;
    }

    public void generate(List<FieldResult> fields) throws IOException {
        generateSyncClass(fields);
        generateAccessWidener(fields);
        generateFieldManifest(fields);
    }

    private void generateSyncClass(List<FieldResult> fields) throws IOException {
        Path javaDir = outputDir.resolve("java/murat/simv2/simulation");
        Files.createDirectories(javaDir);

        StringBuilder sb = new StringBuilder();
        sb.append("package murat.simv2.simulation;\n\n");
        sb.append("import net.minecraft.client.network.ClientPlayerEntity;\n");
        sb.append("import net.minecraft.entity.effect.StatusEffectInstance;\n");
        sb.append("import net.minecraft.entity.player.PlayerAbilities;\n\n");
        sb.append("// Generated by WALA movement field analysis — do not edit\n");
        sb.append("public final class GeneratedSync {\n\n");
        sb.append("    private GeneratedSync() {}\n\n");
        sb.append("    public static void sync(SimulatedPlayer sim, ClientPlayerEntity real) {\n");

        // Group fields by declaring class for readability
        Map<String, List<FieldResult>> byClass = fields.stream()
            .collect(Collectors.groupingBy(FieldResult::declaringClass, LinkedHashMap::new, Collectors.toList()));

        for (var entry : byClass.entrySet()) {
            String className = entry.getKey();
            String shortName = className.substring(className.lastIndexOf('/') + 1);
            sb.append("\n        // ── ").append(shortName).append(" ──\n");

            for (FieldResult field : entry.getValue()) {
                String assignment = generateFieldAssignment(field);
                if (assignment != null) {
                    sb.append("        ").append(assignment).append("\n");
                }
            }
        }

        // Hardcoded sync items that WALA can't resolve (map/collection based)
        sb.append("\n        // ── Composite state (not resolvable by static analysis) ──\n");
        sb.append("        sim.getAttributes().setFrom(real.getAttributes());\n");
        sb.append("\n");
        sb.append("        sim.clearStatusEffects();\n");
        sb.append("        for (StatusEffectInstance effect : real.getActiveStatusEffects().values()) {\n");
        sb.append("            sim.addStatusEffect(new StatusEffectInstance(effect));\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        PlayerAbilities realAbilities = real.getAbilities();\n");
        sb.append("        PlayerAbilities simAbilities = sim.getAbilities();\n");
        sb.append("        simAbilities.flying = realAbilities.flying;\n");
        sb.append("        simAbilities.allowFlying = realAbilities.allowFlying;\n");
        sb.append("        simAbilities.creativeMode = realAbilities.creativeMode;\n");
        sb.append("        simAbilities.invulnerable = realAbilities.invulnerable;\n");
        sb.append("        simAbilities.allowModifyWorld = realAbilities.allowModifyWorld;\n");
        sb.append("        simAbilities.setFlySpeed(realAbilities.getFlySpeed());\n");
        sb.append("        simAbilities.setWalkSpeed(realAbilities.getWalkSpeed());\n");
        sb.append("\n");
        sb.append("        sim.getHungerManager().setFoodLevel(real.getHungerManager().getFoodLevel());\n");
        sb.append("        sim.getHungerManager().setSaturationLevel(real.getHungerManager().getSaturationLevel());\n");
        sb.append("\n");
        sb.append("        for (var slot : net.minecraft.entity.EquipmentSlot.values()) {\n");
        sb.append("            sim.equipStack(slot, real.getEquippedStack(slot).copy());\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        sim.setPose(real.getPose());\n");
        sb.append("\n");
        sb.append("        // DataTracker flags (bit flags in a tracked byte, not individual fields)\n");
        sb.append("        sim.setSprinting(real.isSprinting());\n");
        sb.append("        sim.setSneaking(real.isSneaking());\n");
        sb.append("        sim.setSwimming(real.isSwimming());\n");
        sb.append("        if (real.isGliding()) {\n");
        sb.append("            sim.startGliding();\n");
        sb.append("        } else if (sim.isGliding()) {\n");
        sb.append("            sim.stopGliding();\n");
        sb.append("        }\n");

        sb.append("    }\n");
        sb.append("}\n");

        Files.writeString(javaDir.resolve("GeneratedSync.java"), sb.toString());
        System.out.println("Generated GeneratedSync.java");
    }

    private String generateFieldAssignment(FieldResult field) {
        String name = field.fieldName();

        // Skip excluded and composite fields
        if (AnalysisConfig.EXCLUDED_FIELDS.contains(name)) return null;
        if (isCompositeField(name)) return null;

        // Check if the field is final — skip it (can't reassign final fields)
        if (isFieldFinal(field)) {
            System.out.println("  Skipping final field: " + field.declaringClass() + "." + name);
            return null;
        }

        // Check for public getter/setter
        GetterSetter gs = findGetterSetter(field);

        if (gs.getter != null && gs.setter != null) {
            return "sim." + gs.setter + "(real." + gs.getter + "());";
        } else if (gs.getter != null) {
            // Has getter for reading but no setter — direct field write
            return "sim." + name + " = real." + gs.getter + "();";
        } else {
            // Direct field access both sides
            return "sim." + name + " = real." + name + ";";
        }
    }

    private boolean isFieldFinal(FieldResult field) {
        String className = field.declaringClass();
        TypeReference typeRef = TypeReference.findOrCreate(cha.getScope().getApplicationLoader(), className);
        IClass clazz = cha.lookupClass(typeRef);
        if (clazz == null) return false;

        for (IField f : clazz.getDeclaredInstanceFields()) {
            if (f.getName().toString().equals(field.fieldName())) {
                return f.isFinal();
            }
        }
        return false;
    }

    private boolean isCompositeField(String name) {
        return Set.of(
            "attributes", "activeStatusEffects", "abilities",
            "hungerManager", "equipment", "pose"
        ).contains(name);
    }

    private GetterSetter findGetterSetter(FieldResult field) {
        TypeReference typeRef = TypeReference.findOrCreate(
            cha.getScope().getApplicationLoader(), field.declaringClass());
        IClass clazz = cha.lookupClass(typeRef);
        if (clazz == null) return new GetterSetter(null, null);

        String fieldName = field.fieldName();
        String getterName = null;
        String setterName = null;

        // Common getter patterns
        for (String prefix : List.of("get", "is", "has")) {
            String candidate = prefix + capitalize(fieldName);
            IMethod method = findPublicNoArgMethod(clazz, candidate);
            if (method != null) {
                getterName = candidate;
                break;
            }
        }

        // Common setter patterns
        String setCandidate = "set" + capitalize(fieldName);
        for (IMethod m : clazz.getAllMethods()) {
            if (m.getName().toString().equals(setCandidate)
                && m.isPublic()
                && m.getNumberOfParameters() == 2) { // 'this' + 1 arg
                setterName = setCandidate;
                break;
            }
        }

        return new GetterSetter(getterName, setterName);
    }

    private IMethod findPublicNoArgMethod(IClass clazz, String name) {
        for (IMethod m : clazz.getAllMethods()) {
            if (m.getName().toString().equals(name)
                && m.isPublic()
                && m.getNumberOfParameters() == 1) { // only 'this'
                return m;
            }
        }
        return null;
    }

    private static String capitalize(String s) {
        if (s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private record GetterSetter(String getter, String setter) {}

    private void generateAccessWidener(List<FieldResult> fields) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("accessWidener v2 named\n\n");
        sb.append("# Generated by WALA movement field analysis\n");

        for (FieldResult field : fields) {
            if (isCompositeField(field.fieldName())) continue;
            if (AnalysisConfig.EXCLUDED_FIELDS.contains(field.fieldName())) continue;
            if (isFieldFinal(field)) continue;

            // Emit AW entry for every field that uses direct access in GeneratedSync.
            // We cannot rely on CHA visibility checks because linemapped JARs have
            // access wideners pre-applied (all fields appear public). Instead, mirror
            // the logic in generateFieldAssignment(): if there's no public getter+setter
            // pair, the generated code uses direct field access and needs widening.
            GetterSetter gs = findGetterSetter(field);
            boolean usesDirectAccess = (gs.getter == null || gs.setter == null);
            if (usesDirectAccess) {
                String classPath = field.declaringClass().substring(1); // strip leading 'L'
                String typeDesc = toJvmDescriptor(field.typeDescriptor());
                sb.append("accessible field ")
                    .append(classPath).append(" ")
                    .append(field.fieldName()).append(" ")
                    .append(typeDesc).append("\n");
            }
        }

        Files.writeString(outputDir.resolve("sim-v2.accesswidener"), sb.toString());
        System.out.println("Generated sim-v2.accesswidener");
    }

private String toJvmDescriptor(String walaType) {
        // Primitives: single char (Z, I, F, D, etc.)
        if (walaType.length() == 1) {
            return walaType;
        }
        // Already has L prefix — ensure ; suffix (WALA omits it)
        if (walaType.startsWith("L")) {
            return walaType.endsWith(";") ? walaType : walaType + ";";
        }
        // Array types
        if (walaType.startsWith("[")) {
            return walaType;
        }
        return "L" + walaType + ";";
    }

    private void generateFieldManifest(List<FieldResult> fields) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("# Movement field manifest — generated by WALA analysis\n");
        sb.append("# Format: CATEGORY declaring_class field_name type_descriptor\n\n");

        for (FieldResult field : fields) {
            sb.append(String.format("%-8s %-60s %-30s %s%n",
                field.category(),
                field.declaringClass(),
                field.fieldName(),
                field.typeDescriptor()));
        }

        Files.writeString(outputDir.resolve("movement-fields.txt"), sb.toString());
        System.out.println("Generated movement-fields.txt (" + fields.size() + " fields)");
    }
}
