package murat.simv2.analysis;

import com.ibm.wala.ipa.cha.IClassHierarchy;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class SyncCodeGenerator {

    private final IClassHierarchy cha;
    private final Path outputDir;

    public SyncCodeGenerator(IClassHierarchy cha, Path outputDir) {
        this.cha = cha;
        this.outputDir = outputDir;
    }

    public void generate(List<FieldResult> fields) throws IOException {
        generateSyncClass(fields);
        generateAccessWidener(fields);
        generateFieldManifest(fields);
    }

    private void generateSyncClass(List<FieldResult> fields) throws IOException {
        Path javaDir = outputDir.resolve("java/murat/simv2/simulation");
        Files.createDirectories(javaDir);

        List<FieldResult> includedFields = fields.stream()
            .filter(field -> !AnalysisConfig.EXCLUDED_FIELDS.contains(field.fieldName()))
            .collect(Collectors.toList());

        Map<String, List<FieldResult>> byClass = includedFields.stream()
            .collect(Collectors.groupingBy(FieldResult::declaringClass, LinkedHashMap::new, Collectors.toList()));

        StringBuilder sb = new StringBuilder();
        sb.append("package murat.simv2.simulation;\n\n");
        sb.append("import java.lang.reflect.Array;\n");
        sb.append("import java.lang.reflect.Constructor;\n");
        sb.append("import java.lang.reflect.Field;\n");
        sb.append("import java.lang.reflect.Method;\n");
        sb.append("import java.lang.reflect.Modifier;\n");
        sb.append("import java.util.ArrayList;\n");
        sb.append("import net.minecraft.client.network.ClientPlayerEntity;\n");
        sb.append("import murat.simv2.simulation.sliced.SlicedClientPlayerEntity;\n\n");
        sb.append("// Generated by WALA movement field analysis — do not edit\n");
        sb.append("public final class GeneratedSync {\n");
        sb.append("    private GeneratedSync() {\n");
        sb.append("    }\n\n");

        sb.append("    public static void sync(ClientPlayerEntity real, SlicedClientPlayerEntity sim) {\n");
        sb.append("        if (!(sim instanceof RuntimeSlicedClientPlayerEntity runtimeSim)) {\n");
        sb.append("            throw new IllegalStateException(\"sync target must be RuntimeSlicedClientPlayerEntity\");\n");
        sb.append("        }\n");

        for (var entry : byClass.entrySet()) {
            String className = entry.getKey();
            String shortName = className.substring(className.lastIndexOf('/') + 1);
            sb.append("        // \u2500\u2500 ").append(shortName).append(" \u2500\u2500\n");
            for (FieldResult field : entry.getValue()) {
                String syncLine = generateFieldSyncLine(field);
                sb.append("        ").append(syncLine).append("\n");
            }
        }
        sb.append("    }\n\n");
        sb.append(generatedSyncHelpersSource());
        sb.append("}\n");

        Files.writeString(javaDir.resolve("GeneratedSync.java"), sb.toString());
        System.out.println("Generated GeneratedSync.java");
    }

    private String generateFieldSyncLine(FieldResult field) {
        String name = field.fieldName();
        if (!isJavaIdentifier(name)) {
            throw new IllegalStateException("Unsupported field name for direct generation: " + name);
        }

        String target = "runtimeSim." + name;
        String source = "real." + name;
        if (isPrimitiveDescriptor(field.typeDescriptor())) {
            return target + " = " + source + ";";
        }
        return target + " = copyValue(" + source + ", " + target + ", " + requiresDeepCopy(field) + ");";
    }

    private boolean requiresDeepCopy(FieldResult field) {
        return field.category() == FieldResult.FieldCategory.MOD
            || field.category() == FieldResult.FieldCategory.MOD_REF;
    }

    private boolean isPrimitiveDescriptor(String descriptor) {
        return descriptor != null
            && descriptor.length() == 1
            && "ZBCSIJFD".indexOf(descriptor.charAt(0)) >= 0;
    }

    private boolean isJavaIdentifier(String name) {
        if (name == null || name.isBlank()) {
            return false;
        }
        if (!Character.isJavaIdentifierStart(name.charAt(0))) {
            return false;
        }
        for (int i = 1; i < name.length(); i++) {
            if (!Character.isJavaIdentifierPart(name.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    private String generatedSyncHelpersSource() {
        return """

    @SuppressWarnings("unchecked")
    private static <T> T copyValue(T realValue, T simValue, boolean deepCopy) {
        if (!deepCopy) {
            return realValue;
        }
        try {
            return (T) syncValue(realValue, simValue, new ArrayList<>());
        } catch (ReflectiveOperationException ex) {
            throw new IllegalStateException("Failed to deep copy sync value", ex);
        }
    }

    private static Object syncValue(Object realValue, Object simValue, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        if (realValue == null) {
            return null;
        }
        if (isSimpleValueType(realValue.getClass())) {
            return cloneSimpleValue(realValue);
        }
        for (SeenPair pair : seen) {
            if (pair.matches(realValue, simValue)) {
                return simValue != null ? simValue : realValue;
            }
        }
        seen.add(new SeenPair(realValue, simValue));

        if (realValue.getClass().isArray()) {
            return syncArray(realValue, simValue, seen);
        }
        if (realValue instanceof java.util.Map<?, ?> realMap) {
            return syncMap(realMap, simValue, seen);
        }
        if (realValue instanceof java.util.Collection<?> realCollection) {
            return syncCollection(realCollection, simValue, seen);
        }

        Object target = simValue;
        if (target == null) {
            Object cloned = tryCloneObject(realValue);
            if (cloned != null) {
                return cloned;
            }
            target = instantiateLike(realValue.getClass());
            if (target == null) {
                return realValue;
            }
        }

        deepSyncObject(realValue, target, seen);
        return target;
    }

    private static void deepSyncObject(Object realValue, Object simValue, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        Class<?> current = realValue.getClass();
        while (current != null && current != Object.class) {
            for (Field field : current.getDeclaredFields()) {
                if (Modifier.isStatic(field.getModifiers())) {
                    continue;
                }
                field.setAccessible(true);
                Object realFieldValue = field.get(realValue);
                Object simFieldValue = field.get(simValue);
                Object copied = syncValue(realFieldValue, simFieldValue, seen);
                if (!Modifier.isFinal(field.getModifiers()) && copied != simFieldValue) {
                    field.set(simValue, copied);
                }
            }
            current = current.getSuperclass();
        }
    }

    private static Object syncArray(Object realArray, Object simArray, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        int length = Array.getLength(realArray);
        Class<?> componentType = realArray.getClass().getComponentType();
        Object target = simArray;
        if (target == null || !target.getClass().isArray() || Array.getLength(target) != length) {
            target = Array.newInstance(componentType, length);
        }
        for (int i = 0; i < length; i++) {
            Object realElement = Array.get(realArray, i);
            Object simElement = Array.get(target, i);
            Array.set(target, i, syncValue(realElement, simElement, seen));
        }
        return target;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private static Object syncMap(java.util.Map<?, ?> realMap, Object simValue, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        java.util.Map target = (simValue instanceof java.util.Map<?, ?> existing)
            ? (java.util.Map) existing
            : instantiateMap(realMap.getClass());
        if (target == null) {
            target = new java.util.LinkedHashMap();
        }
        target.clear();
        for (java.util.Map.Entry<?, ?> entry : realMap.entrySet()) {
            Object key = syncValue(entry.getKey(), null, seen);
            Object value = syncValue(entry.getValue(), null, seen);
            target.put(key, value);
        }
        return target;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private static Object syncCollection(java.util.Collection<?> realCollection, Object simValue, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        java.util.Collection target = (simValue instanceof java.util.Collection<?> existing)
            ? (java.util.Collection) existing
            : instantiateCollection(realCollection.getClass());
        if (target == null) {
            target = new java.util.ArrayList();
        }
        target.clear();
        for (Object value : realCollection) {
            target.add(syncValue(value, null, seen));
        }
        return target;
    }

    private static Object cloneSimpleValue(Object value) throws ReflectiveOperationException {
        Object cloned = tryCloneObject(value);
        return cloned != null ? cloned : value;
    }

    private static Object tryCloneObject(Object value) throws ReflectiveOperationException {
        if (value == null) {
            return null;
        }
        try {
            Method copy = value.getClass().getDeclaredMethod("copy");
            copy.setAccessible(true);
            return copy.invoke(value);
        } catch (NoSuchMethodException ignored) {
        }
        try {
            Constructor<?> copyCtor = value.getClass().getDeclaredConstructor(value.getClass());
            copyCtor.setAccessible(true);
            return copyCtor.newInstance(value);
        } catch (NoSuchMethodException ignored) {
        }
        return null;
    }

    private static Object instantiateLike(Class<?> type) throws ReflectiveOperationException {
        try {
            Constructor<?> ctor = type.getDeclaredConstructor();
            ctor.setAccessible(true);
            return ctor.newInstance();
        } catch (NoSuchMethodException ignored) {
            return null;
        }
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private static java.util.Map instantiateMap(Class<?> type) throws ReflectiveOperationException {
        Object instance = instantiateLike(type);
        return instance instanceof java.util.Map<?, ?> map ? (java.util.Map) map : null;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private static java.util.Collection instantiateCollection(Class<?> type) throws ReflectiveOperationException {
        Object instance = instantiateLike(type);
        return instance instanceof java.util.Collection<?> collection ? (java.util.Collection) collection : null;
    }

    private static boolean isSimpleValueType(Class<?> type) {
        return type.isPrimitive()
            || type.isEnum()
            || Number.class.isAssignableFrom(type)
            || Boolean.class == type
            || Character.class == type
            || String.class == type
            || java.util.UUID.class == type
            || type.getName().startsWith("net.minecraft.util.math.Vec")
            || type.getName().startsWith("net.minecraft.util.math.BlockPos")
            || type.getName().startsWith("net.minecraft.util.math.Box")
            || type.getName().startsWith("net.minecraft.text.Text")
            || type.getName().startsWith("java.util.Optional");
    }

    private record SeenPair(Object realValue, Object simValue) {
        private boolean matches(Object otherReal, Object otherSim) {
            return realValue == otherReal && simValue == otherSim;
        }
    }
""";
    }

    private void generateAccessWidener(List<FieldResult> fields) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("accessWidener v2 named\n\n");
        sb.append("# Generated by WALA movement field analysis\n");

        for (FieldResult field : fields) {
            if (AnalysisConfig.EXCLUDED_FIELDS.contains(field.fieldName())) continue;
            String classPath = field.declaringClass().substring(1); // strip leading 'L'
            String typeDesc = toJvmDescriptor(field.typeDescriptor());
            sb.append("accessible field ")
                .append(classPath).append(" ")
                .append(field.fieldName()).append(" ")
                .append(typeDesc).append("\n");
        }
        // Required by sliced movement code path in SlicedEntity.
        sb.append("accessible method net/minecraft/entity/Entity isControlledByMainPlayer ()Z\n");

        String awSource = sb.toString();
        Files.writeString(outputDir.resolve("sim-v2.accesswidener"), awSource);
        Path mainResources = outputDir.getParent().resolve("resources/sim-v2.accesswidener");
        Files.writeString(mainResources, awSource);
        System.out.println("Generated sim-v2.accesswidener");
    }

    private String toJvmDescriptor(String walaType) {
        if (walaType.length() == 1) {
            return walaType;
        }
        if (walaType.startsWith("L")) {
            return walaType.endsWith(";") ? walaType : walaType + ";";
        }
        if (walaType.startsWith("[")) {
            return walaType;
        }
        return "L" + walaType + ";";
    }

    private void generateFieldManifest(List<FieldResult> fields) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("# Movement field manifest — generated by WALA analysis\n");
        sb.append("# Format: CATEGORY declaring_class field_name type_descriptor\n\n");

        for (FieldResult field : fields) {
            sb.append(String.format("%-8s %-60s %-30s %s%n",
                field.category(),
                field.declaringClass(),
                field.fieldName(),
                field.typeDescriptor()));
        }

        Files.writeString(outputDir.resolve("movement-fields.txt"), sb.toString());
        System.out.println("Generated movement-fields.txt (" + fields.size() + " fields)");
    }
}
