package murat.simv2.analysis;

import com.ibm.wala.classLoader.IClass;
import com.ibm.wala.classLoader.IField;
import com.ibm.wala.classLoader.IMethod;
import com.ibm.wala.ipa.cha.IClassHierarchy;
import com.ibm.wala.types.TypeReference;
import spoon.Launcher;
import spoon.reflect.code.*;
import spoon.reflect.declaration.*;
import spoon.reflect.factory.Factory;
import spoon.reflect.reference.CtTypeReference;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

public class SyncCodeGenerator {

    private final IClassHierarchy cha;
    private final Path outputDir;
    private final Factory factory;

    public SyncCodeGenerator(IClassHierarchy cha, Path outputDir) {
        this.cha = cha;
        this.outputDir = outputDir;
        this.factory = new Launcher().getFactory();
    }

    public void generate(List<FieldResult> fields) throws IOException {
        generateSyncClass(fields);
        generateAccessWidener(fields);
        generateFieldManifest(fields);
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private void generateSyncClass(List<FieldResult> fields) throws IOException {
        Path javaDir = outputDir.resolve("java/murat/simv2/simulation");
        Files.createDirectories(javaDir);

        // Build class via Spoon AST
        CtClass syncClass = factory.Core().createClass();
        syncClass.setSimpleName("GeneratedSync");
        syncClass.addModifier(ModifierKind.PUBLIC);
        syncClass.addModifier(ModifierKind.FINAL);

        // Private no-arg constructor
        CtConstructor ctor = factory.Core().createConstructor();
        ctor.addModifier(ModifierKind.PRIVATE);
        ctor.setBody(factory.createBlock());
        syncClass.addConstructor(ctor);

        // public static void sync(ClientPlayerEntity real, SlicedClientPlayerEntity sim)
        CtMethod syncMethod = factory.createMethod();
        syncMethod.setSimpleName("sync");
        syncMethod.addModifier(ModifierKind.PUBLIC);
        syncMethod.addModifier(ModifierKind.STATIC);
        syncMethod.setType(factory.Type().voidPrimitiveType());

        CtParameter realParam = factory.Core().createParameter();
        realParam.setSimpleName("real");
        CtTypeReference realType = factory.Core().createTypeReference();
        realType.setSimpleName("ClientPlayerEntity");
        realParam.setType(realType);
        syncMethod.addParameter(realParam);

        CtParameter simParam = factory.Core().createParameter();
        simParam.setSimpleName("sim");
        CtTypeReference simType = factory.Core().createTypeReference();
        simType.setSimpleName("SlicedClientPlayerEntity");
        simParam.setType(simType);
        syncMethod.addParameter(simParam);

        CtBlock body = factory.createBlock();
        syncMethod.setBody(body);

        // Dynamic field assignments grouped by declaring class
        Map<String, List<FieldResult>> byClass = fields.stream()
            .collect(Collectors.groupingBy(FieldResult::declaringClass, LinkedHashMap::new, Collectors.toList()));

        for (var entry : byClass.entrySet()) {
            String className = entry.getKey();
            String shortName = className.substring(className.lastIndexOf('/') + 1);
            addComment(body, "── " + shortName + " ──");

            for (FieldResult field : entry.getValue()) {
                String syncCall = generateFieldSyncCall(field);
                if (syncCall != null) {
                    addSnippet(body, syncCall);
                }
            }
        }

        syncClass.addMethod(syncMethod);

        // Output: package + imports header, then Spoon-rendered class body
        StringBuilder sb = new StringBuilder();
        sb.append("package murat.simv2.simulation;\n\n");
        sb.append("import java.lang.reflect.Array;\n");
        sb.append("import java.lang.reflect.Constructor;\n");
        sb.append("import java.lang.reflect.Field;\n");
        sb.append("import java.lang.reflect.Method;\n");
        sb.append("import java.lang.reflect.Modifier;\n");
        sb.append("import java.util.ArrayList;\n");
        sb.append("import net.minecraft.client.network.ClientPlayerEntity;\n");
        sb.append("import murat.simv2.simulation.sliced.SlicedClientPlayerEntity;\n\n");
        sb.append("// Generated by WALA movement field analysis — do not edit\n");
        sb.append(appendGeneratedSyncHelpers(syncClass.toString()));

        Files.writeString(javaDir.resolve("GeneratedSync.java"), sb.toString());
        System.out.println("Generated GeneratedSync.java");
    }

    private void addComment(CtBlock<?> block, String text) {
        CtComment comment = factory.Core().createComment();
        comment.setCommentType(CtComment.CommentType.INLINE);
        comment.setContent(text);
        block.addStatement(comment);
    }

    private void addSnippet(CtBlock<?> block, String code) {
        CtCodeSnippetStatement stmt = factory.Core().createCodeSnippetStatement();
        // Strip trailing semicolon — CtCodeSnippetStatement adds one during rendering
        String value = code.endsWith(";") ? code.substring(0, code.length() - 1) : code;
        stmt.setValue(value);
        block.addStatement(stmt);
    }

    private String generateFieldSyncCall(FieldResult field) {
        String name = field.fieldName();

        // Skip excluded fields
        if (AnalysisConfig.EXCLUDED_FIELDS.contains(name)) return null;
        return "syncMember(real, sim, \"" + escapeJavaString(name) + "\")";
    }

    private boolean isFieldFinal(FieldResult field) {
        String className = field.declaringClass();
        TypeReference typeRef = TypeReference.findOrCreate(cha.getScope().getApplicationLoader(), className);
        IClass clazz = cha.lookupClass(typeRef);
        if (clazz == null) return false;

        for (IField f : clazz.getDeclaredInstanceFields()) {
            if (f.getName().toString().equals(field.fieldName())) {
                return f.isFinal();
            }
        }
        return false;
    }

    private boolean isCompositeField(String name) {
        return Set.of(
            "attributes", "activeStatusEffects", "abilities",
            "hungerManager", "equipment", "pose"
        ).contains(name);
    }

    private GetterSetter findGetterSetter(FieldResult field) {
        TypeReference typeRef = TypeReference.findOrCreate(
            cha.getScope().getApplicationLoader(), field.declaringClass());
        IClass clazz = cha.lookupClass(typeRef);
        if (clazz == null) return new GetterSetter(null, null);

        String fieldName = field.fieldName();
        String getterName = null;
        String setterName = null;

        // Common getter patterns
        for (String prefix : List.of("get", "is", "has")) {
            String candidate = prefix + capitalize(fieldName);
            IMethod method = findPublicNoArgMethod(clazz, candidate);
            if (method != null) {
                getterName = candidate;
                break;
            }
        }

        // Common setter patterns
        String setCandidate = "set" + capitalize(fieldName);
        for (IMethod m : clazz.getAllMethods()) {
            if (m.getName().toString().equals(setCandidate)
                && m.isPublic()
                && m.getNumberOfParameters() == 2) { // 'this' + 1 arg
                setterName = setCandidate;
                break;
            }
        }

        return new GetterSetter(getterName, setterName);
    }

    private IMethod findPublicNoArgMethod(IClass clazz, String name) {
        for (IMethod m : clazz.getAllMethods()) {
            if (m.getName().toString().equals(name)
                && m.isPublic()
                && m.getNumberOfParameters() == 1) { // only 'this'
                return m;
            }
        }
        return null;
    }

    private static String capitalize(String s) {
        if (s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private record GetterSetter(String getter, String setter) {}

    private String appendGeneratedSyncHelpers(String syncClassSource) {
        int closingBrace = syncClassSource.lastIndexOf('}');
        if (closingBrace < 0) {
            return syncClassSource;
        }
        return syncClassSource.substring(0, closingBrace)
            + generatedSyncHelpersSource()
            + "\n}\n";
    }

    private String generatedSyncHelpersSource() {
        return """

    private static void syncMember(Object realOwner, Object simOwner, String memberName) {
        try {
            MemberAccess realAccess = findReadableMember(realOwner.getClass(), memberName);
            MemberAccess simAccess = findAnyMember(simOwner.getClass(), memberName);
            if (realAccess == null || simAccess == null) {
                return;
            }

            Object realValue = realAccess.read(realOwner);
            if (realValue == null) {
                if (simAccess.canWrite()) {
                    simAccess.write(simOwner, null);
                }
                return;
            }

            Object simValue = simAccess.read(simOwner);
            Object synced = syncValue(realValue, simValue, new ArrayList<>());
            if (simAccess.canWrite() && synced != simValue) {
                simAccess.write(simOwner, synced);
            }
        } catch (ReflectiveOperationException ex) {
            throw new IllegalStateException("Failed to sync member '" + memberName + "'", ex);
        }
    }

    private static Object syncValue(Object realValue, Object simValue, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        if (realValue == null) {
            return null;
        }
        if (isSimpleValueType(realValue.getClass())) {
            return cloneSimpleValue(realValue);
        }
        for (SeenPair pair : seen) {
            if (pair.matches(realValue, simValue)) {
                return simValue != null ? simValue : realValue;
            }
        }
        seen.add(new SeenPair(realValue, simValue));

        if (realValue.getClass().isArray()) {
            return syncArray(realValue, simValue, seen);
        }
        if (realValue instanceof java.util.Map<?, ?> realMap) {
            return syncMap(realMap, simValue, seen);
        }
        if (realValue instanceof java.util.Collection<?> realCollection) {
            return syncCollection(realCollection, simValue, seen);
        }

        Object target = simValue;
        if (target == null) {
            Object cloned = tryCloneObject(realValue);
            if (cloned != null) {
                return cloned;
            }
            target = instantiateLike(realValue.getClass());
            if (target == null) {
                return realValue;
            }
        }

        deepSyncObject(realValue, target, seen);
        return target;
    }

    private static void deepSyncObject(Object realValue, Object simValue, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        Class<?> current = realValue.getClass();
        while (current != null && current != Object.class) {
            for (Field field : current.getDeclaredFields()) {
                if (Modifier.isStatic(field.getModifiers())) {
                    continue;
                }
                syncMember(realValue, simValue, field.getName());
            }
            current = current.getSuperclass();
        }
    }

    private static Object syncArray(Object realArray, Object simArray, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        int length = Array.getLength(realArray);
        Class<?> componentType = realArray.getClass().getComponentType();
        Object target = simArray;
        if (target == null || !target.getClass().isArray() || Array.getLength(target) != length) {
            target = Array.newInstance(componentType, length);
        }
        for (int i = 0; i < length; i++) {
            Object realElement = Array.get(realArray, i);
            Object simElement = Array.get(target, i);
            Array.set(target, i, syncValue(realElement, simElement, seen));
        }
        return target;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private static Object syncMap(java.util.Map<?, ?> realMap, Object simValue, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        java.util.Map target = (simValue instanceof java.util.Map<?, ?> existing)
            ? (java.util.Map) existing
            : instantiateMap(realMap.getClass());
        if (target == null) {
            target = new java.util.LinkedHashMap();
        }
        target.clear();
        for (java.util.Map.Entry<?, ?> entry : realMap.entrySet()) {
            Object key = syncValue(entry.getKey(), null, seen);
            Object value = syncValue(entry.getValue(), null, seen);
            target.put(key, value);
        }
        return target;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private static Object syncCollection(java.util.Collection<?> realCollection, Object simValue, ArrayList<SeenPair> seen) throws ReflectiveOperationException {
        java.util.Collection target = (simValue instanceof java.util.Collection<?> existing)
            ? (java.util.Collection) existing
            : instantiateCollection(realCollection.getClass());
        if (target == null) {
            target = new java.util.ArrayList();
        }
        target.clear();
        for (Object value : realCollection) {
            target.add(syncValue(value, null, seen));
        }
        return target;
    }

    private static Object cloneSimpleValue(Object value) throws ReflectiveOperationException {
        Object cloned = tryCloneObject(value);
        return cloned != null ? cloned : value;
    }

    private static Object tryCloneObject(Object value) throws ReflectiveOperationException {
        if (value == null) {
            return null;
        }
        try {
            Method copy = value.getClass().getDeclaredMethod("copy");
            copy.setAccessible(true);
            return copy.invoke(value);
        } catch (NoSuchMethodException ignored) {
        }
        try {
            Constructor<?> copyCtor = value.getClass().getDeclaredConstructor(value.getClass());
            copyCtor.setAccessible(true);
            return copyCtor.newInstance(value);
        } catch (NoSuchMethodException ignored) {
        }
        return null;
    }

    private static Object instantiateLike(Class<?> type) throws ReflectiveOperationException {
        try {
            Constructor<?> ctor = type.getDeclaredConstructor();
            ctor.setAccessible(true);
            return ctor.newInstance();
        } catch (NoSuchMethodException ignored) {
            return null;
        }
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private static java.util.Map instantiateMap(Class<?> type) throws ReflectiveOperationException {
        Object instance = instantiateLike(type);
        return instance instanceof java.util.Map<?, ?> map ? (java.util.Map) map : null;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    private static java.util.Collection instantiateCollection(Class<?> type) throws ReflectiveOperationException {
        Object instance = instantiateLike(type);
        return instance instanceof java.util.Collection<?> collection ? (java.util.Collection) collection : null;
    }

    private static boolean isSimpleValueType(Class<?> type) {
        return type.isPrimitive()
            || type.isEnum()
            || Number.class.isAssignableFrom(type)
            || Boolean.class == type
            || Character.class == type
            || String.class == type
            || java.util.UUID.class == type
            || type.getName().startsWith("net.minecraft.util.math.Vec")
            || type.getName().startsWith("net.minecraft.util.math.BlockPos")
            || type.getName().startsWith("net.minecraft.util.math.Box")
            || type.getName().startsWith("net.minecraft.text.Text")
            || type.getName().startsWith("java.util.Optional");
    }

    private static MemberAccess findReadableMember(Class<?> ownerType, String memberName) {
        MemberAccess getterAccess = findGetter(ownerType, memberName);
        if (getterAccess != null) {
            return getterAccess;
        }
        return findField(ownerType, memberName);
    }

    private static MemberAccess findAnyMember(Class<?> ownerType, String memberName) {
        MemberAccess getterAccess = findGetter(ownerType, memberName);
        MemberAccess fieldAccess = findField(ownerType, memberName);
        if (fieldAccess != null) {
            return fieldAccess.withFallbackGetter(getterAccess);
        }
        return getterAccess;
    }

    private static MemberAccess findGetter(Class<?> ownerType, String memberName) {
        String capitalized = Character.toUpperCase(memberName.charAt(0)) + memberName.substring(1);
        for (String prefix : new String[] { "get", "is", "has" }) {
            try {
                Method getter = ownerType.getMethod(prefix + capitalized);
                getter.setAccessible(true);
                return MemberAccess.forGetter(getter);
            } catch (NoSuchMethodException ignored) {
            }
        }
        return null;
    }

    private static MemberAccess findField(Class<?> ownerType, String memberName) {
        Class<?> current = ownerType;
        while (current != null && current != Object.class) {
            try {
                Field field = current.getDeclaredField(memberName);
                field.setAccessible(true);
                return MemberAccess.forField(field);
            } catch (NoSuchFieldException ignored) {
                current = current.getSuperclass();
            }
        }
        return null;
    }

    private record SeenPair(Object realValue, Object simValue) {
        private boolean matches(Object otherReal, Object otherSim) {
            return realValue == otherReal && simValue == otherSim;
        }
    }

    private static final class MemberAccess {
        private final Field field;
        private final Method getter;
        private final Method setter;
        private final MemberAccess fallbackGetter;

        private MemberAccess(Field field, Method getter, Method setter, MemberAccess fallbackGetter) {
            this.field = field;
            this.getter = getter;
            this.setter = setter;
            this.fallbackGetter = fallbackGetter;
        }

        private static MemberAccess forField(Field field) {
            Method setter = findSetter(field.getDeclaringClass(), field.getName(), field.getType());
            return new MemberAccess(field, null, setter, null);
        }

        private static MemberAccess forGetter(Method getter) {
            Method setter = findSetter(getter.getDeclaringClass(), inferMemberName(getter), getter.getReturnType());
            return new MemberAccess(null, getter, setter, null);
        }

        private MemberAccess withFallbackGetter(MemberAccess fallback) {
            return new MemberAccess(field, getter, setter, fallback);
        }

        private Object read(Object owner) throws ReflectiveOperationException {
            if (field != null) {
                return field.get(owner);
            }
            if (getter != null) {
                return getter.invoke(owner);
            }
            return fallbackGetter != null ? fallbackGetter.read(owner) : null;
        }

        private boolean canWrite() {
            return setter != null || (field != null && !Modifier.isFinal(field.getModifiers()));
        }

        private void write(Object owner, Object value) throws ReflectiveOperationException {
            if (setter != null) {
                setter.invoke(owner, value);
            } else if (field != null && !Modifier.isFinal(field.getModifiers())) {
                field.set(owner, value);
            }
        }

        private static String inferMemberName(Method getter) {
            String name = getter.getName();
            if (name.startsWith("get") || name.startsWith("has")) {
                return Character.toLowerCase(name.charAt(3)) + name.substring(4);
            }
            if (name.startsWith("is")) {
                return Character.toLowerCase(name.charAt(2)) + name.substring(3);
            }
            return name;
        }

        private static Method findSetter(Class<?> ownerType, String memberName, Class<?> parameterType) {
            String setterName = "set" + Character.toUpperCase(memberName.charAt(0)) + memberName.substring(1);
            Class<?> current = ownerType;
            while (current != null && current != Object.class) {
                for (Method method : current.getDeclaredMethods()) {
                    if (!method.getName().equals(setterName) || method.getParameterCount() != 1) {
                        continue;
                    }
                    Class<?> candidateType = method.getParameterTypes()[0];
                    if (candidateType.isAssignableFrom(parameterType) || parameterType.isAssignableFrom(candidateType)) {
                        method.setAccessible(true);
                        return method;
                    }
                }
                current = current.getSuperclass();
            }
            return null;
        }
    }
""";
    }

    private String escapeJavaString(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private void generateAccessWidener(List<FieldResult> fields) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("accessWidener v2 named\n\n");
        sb.append("# Generated by WALA movement field analysis\n");

        for (FieldResult field : fields) {
            if (isCompositeField(field.fieldName())) continue;
            if (AnalysisConfig.EXCLUDED_FIELDS.contains(field.fieldName())) continue;
            if (isFieldFinal(field)) continue;

            // Emit AW entry for every field that uses direct access in GeneratedSync.
            // We cannot rely on CHA visibility checks because linemapped JARs have
            // access wideners pre-applied (all fields appear public). Instead, mirror
            // the logic in generateFieldAssignment(): if there's no public getter+setter
            // pair, the generated code uses direct field access and needs widening.
            GetterSetter gs = findGetterSetter(field);
            boolean usesDirectAccess = (gs.getter == null || gs.setter == null);
            if (usesDirectAccess) {
                String classPath = field.declaringClass().substring(1); // strip leading 'L'
                String typeDesc = toJvmDescriptor(field.typeDescriptor());
                sb.append("accessible field ")
                    .append(classPath).append(" ")
                    .append(field.fieldName()).append(" ")
                    .append(typeDesc).append("\n");
            }
        }

        Files.writeString(outputDir.resolve("sim-v2.accesswidener"), sb.toString());
        System.out.println("Generated sim-v2.accesswidener");
    }

    private String toJvmDescriptor(String walaType) {
        // Primitives: single char (Z, I, F, D, etc.)
        if (walaType.length() == 1) {
            return walaType;
        }
        // Already has L prefix — ensure ; suffix (WALA omits it)
        if (walaType.startsWith("L")) {
            return walaType.endsWith(";") ? walaType : walaType + ";";
        }
        // Array types
        if (walaType.startsWith("[")) {
            return walaType;
        }
        return "L" + walaType + ";";
    }

    private void generateFieldManifest(List<FieldResult> fields) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("# Movement field manifest — generated by WALA analysis\n");
        sb.append("# Format: CATEGORY declaring_class field_name type_descriptor\n\n");

        for (FieldResult field : fields) {
            sb.append(String.format("%-8s %-60s %-30s %s%n",
                field.category(),
                field.declaringClass(),
                field.fieldName(),
                field.typeDescriptor()));
        }

        Files.writeString(outputDir.resolve("movement-fields.txt"), sb.toString());
        System.out.println("Generated movement-fields.txt (" + fields.size() + " fields)");
    }
}
